- .dockerignore
- .gitignore
- Dockerfile
- README.md
@arose Here is a pull-request for the Docker example code. This yields a completely containerized runtime of your build-canvas results
> Dev cc docker

- src/mol-plugin/skin/base/components/line-graph.scss
- src/mol-plugin/ui/controls/line-graph/line-graph-component.tsx
- src/mol-plugin/ui/controls/line-graph/point-component.tsx
User is able to continue dragging a point while they go out the bounds of the canvas. I also improved performance while user is dragging point, and you no longer get pauses.
> User can continue dragging after leaving canvas & Bug fixes

- src/mol-model/structure/structure/unit/links/inter-compute.ts
- src/mol-model/structure/structure/unit/links/intra-compute.ts
@dsehnal this is my attempt to fix e.g. metal bonds in 4zjx
> fix struct_conn use for bond computation

- src/mol-canvas3d/canvas3d.ts
- src/mol-state/object.ts
- src/mol-state/state.ts
- src/mol-util/param-definition.ts
Adds the ability to "normalize" parameter values based on the definition.
> ParamDefinition.normalizePrams

- src/mol-canvas3d/canvas3d.ts
- src/mol-canvas3d/passes/pick.ts
- src/mol-plugin/context.ts
adds support for passing ``Canvas3DContext`` to ``PluginContext`` and "relative viewport frame"  to ``Canvas3D``
> Multi-canvas support for PluginContext

- src/extensions/geo-export/glb-exporter.ts
- src/extensions/geo-export/obj-exporter.ts
This should resolve #176.
Am I supposed to use `transparencyAverage` somewhere?
I don't think it's a big enough change to warrant an update in the changelog. But let me know.
> Add per-group transparency support to geometry exporters

- CHANGELOG.md
- src/mol-model-props/sequence/best-database-mapping.ts
- src/mol-model-props/sequence/themes/best-database-mapping.ts
- src/mol-model/structure/structure/util/superposition-db-mapping.ts
- src/mol-plugin-ui/structure/superposition.tsx
- src/mol-plugin/behavior/dynamic/custom-props.ts
- src/mol-plugin/behavior/dynamic/custom-props/sequence/best-database-mapping.ts
- src/mol-plugin/spec.ts
Reading of ``atom_site.db_name/_acc/_num/_res`` CIF fields with basic theme and superposition support.
https://user-images.githubusercontent.com/21145776/119504494-4f54b080-bd6c-11eb-8880-e4215340cd05.mp4
> Basic sequence mapping support

- CHANGELOG.md
- src/extensions/geo-export/glb-exporter.ts
- src/extensions/geo-export/mesh-exporter.ts
- src/extensions/geo-export/obj-exporter.ts
- src/extensions/geo-export/usdz-exporter.ts
> Add overpaint support to geometry exporters

- CHANGELOG.md
- src/mol-canvas3d/canvas3d.ts
- src/mol-canvas3d/controls/trackball.ts
- src/mol-model/structure/structure/structure.ts
- src/mol-util/input/input-observer.ts
- Improve pinch zoom
- Normalize wheel speed across platforms/browsers
- Override Safari pinch gesture to act as zoom
> Input observer improvements

- CHANGELOG.md
- src/mol-data/util/hash-functions.ts
- src/mol-geo/geometry/mesh/mesh.ts
- src/mol-repr/structure/visual/gaussian-density-volume.ts
- src/mol-repr/structure/visual/gaussian-surface-mesh.ts
- src/mol-repr/structure/visual/gaussian-surface-wireframe.ts
- src/mol-repr/structure/visual/molecular-surface-mesh.ts
- src/mol-repr/structure/visual/util/common.ts
Automatic border smoothing for molecular -surface visuals that have the ``includeParent`` option enabled.
> Mesh processing: border smoothing

- src/apps/docking-viewer/viewport.tsx
- src/mol-geo/geometry/base.ts
- src/mol-plugin-state/helpers/structure-substance.ts
- src/mol-plugin-state/manager/structure/component.ts
- src/mol-plugin-state/transforms/representation.ts
- src/mol-theme/substance.ts
- src/mol-util/material.ts
Uses object instead of packed integer to represent materials.
> Refactor Material Representation

- CHANGELOG.md
- src/mol-plugin-ui/hooks/use-behavior.ts
- src/mol-plugin-ui/plugin.tsx
- src/mol-plugin-ui/skin/base/components/misc.scss
https://user-images.githubusercontent.com/21145776/146004535-67c1b005-e80b-4732-b27f-41112a818ee4.mp4
> Drag and Drop Overlay

- CHANGELOG.md
- src/mol-plugin/config.ts
- src/mol-plugin/features.ts
> PluginFeatureDetection and disable WBOIT in Safari

- src/mol-canvas3d/canvas3d.ts
- src/mol-canvas3d/passes/draw.ts
- src/mol-canvas3d/passes/image.ts
- src/mol-canvas3d/passes/marking.ts
- src/mol-canvas3d/passes/multi-sample.ts
- src/mol-geo/geometry/_spec/marker.spec.ts
- src/mol-geo/geometry/marker-data.ts
- src/mol-gl/renderer.ts
- src/mol-plugin-state/manager/structure/selection.ts
- src/mol-plugin/behavior/dynamic/representation.ts
- src/mol-repr/structure/complex-representation.ts
- src/mol-repr/structure/units-representation.ts
- various marker improvements
- enable marking pass by default (a bit expensive for cellpack models but would like to test this more widely)
- improve temporal multi-sample handling
> Marker improvements

- CHANGELOG.md
- src/mol-model-formats/structure/mol2.ts
- src/mol-model-formats/structure/property/bonds/index-pair.ts
- src/mol-model/structure/structure/unit/bonds/common.ts
- src/mol-model/structure/structure/unit/bonds/inter-compute.ts
- src/mol-model/structure/structure/unit/bonds/intra-compute.ts
- Improve bond assignment from ``IndexPairBonds``
- Add ``id`` for mapping to source data
- Fix assignment of bonds with unphysical length
> IndexPairBonds improvements

- CHANGELOG.md
- src/extensions/mp4-export/encoder.ts
- src/mol-plugin-state/animation/built-in/camera-spin.ts
- src/mol-plugin-state/animation/model.ts
- src/mol-plugin-state/manager/animation.ts
- src/mol-plugin/animation-loop.ts
- Fix camera stutter for "camera spin"
Closes #339
> Pass animation info to state animations

- package-lock.json
- package.json
- src/mol-plugin-state/manager/snapshots.ts
- src/mol-plugin-state/transforms/model.ts
- src/mol-plugin-ui/controls.tsx
- src/mol-plugin/util/toast.ts
- src/mol-state/tree/immutable.ts
- src/mol-state/tree/transient.ts
> bump immutable to 4.0

- CHANGELOG.md
- src/apps/viewer/app.ts
- src/mol-model/volume/volume.ts
- src/mol-plugin-state/formats/volume.ts
- src/servers/volume/config.ts
- src/servers/volume/query.ts
- Support automatic iso-value adjustment for VolumeServer data in ``Viewer.loadVolumeFromUrl``
> Volume server data fix

- CHANGELOG.md
- src/mol-canvas3d/helper/interaction-events.ts
What do you think? Would it cause any issues? @dsehnal
> emit drag event whenever started within viewport

- CHANGELOG.md
- src/mol-plugin/behavior/static/representation.ts
- src/mol-state/transform.ts
> Fix visual visibility edge case

- CHANGELOG.md
- src/mol-canvas3d/canvas3d.ts
- src/mol-plugin-state/manager/interactivity.ts
- src/mol-plugin-ui/sequence/sequence.tsx
- src/mol-plugin/behavior/dynamic/representation.ts
- Apply making in the main render loop instead of calling the draw function eagerly each time marking changes.
- Use ``throttleTime`` instead of ``debounceTime`` in the sequence viewer (felt better overall).
Should fix #382.
> Resolve marking in main render loop

- src/mol-canvas3d/camera.ts
- src/mol-geo/geometry/text/text-builder.ts
- src/mol-gl/shader-code.ts
- src/mol-gl/webgl/buffer.ts
- src/mol-io/common/binary-cif/classifier.ts
- src/mol-io/common/binary-cif/decoder.ts
- src/mol-io/writer/cif/encoder.ts
- src/mol-model/sequence/sequence.ts
- src/mol-plugin-state/actions/structure.ts
- src/mol-plugin-state/actions/volume.ts
- src/mol-plugin-state/helpers/structure-component.ts
- src/mol-plugin-state/transforms/data.ts
- src/mol-plugin-state/transforms/model.ts
- src/mol-script/language/parser.ts
- src/mol-util/zip/deflate.ts
> make use of assertUnreachable

- CHANGELOG.md
- src/mol-model-formats/structure/pdb/atom-site.ts
- src/mol-model-formats/structure/pdb/to-cif.ts
- handle non unique atom and chain names
- fixes #156
> improve pdb parsing

- CHANGELOG.md
- src/mol-geo/geometry/cylinders/cylinders.ts
- src/mol-geo/geometry/mesh/mesh.ts
- src/mol-geo/geometry/spheres/spheres.ts
- src/mol-geo/geometry/texture-mesh/texture-mesh.ts
- src/mol-gl/shader/chunks/wboit-write.glsl.ts
- src/mol-repr/util.ts
- for mesh, spheres, cylinders, texture-mesh geometries
> add allowTransparentBackfaces parameter

- CHANGELOG.md
- src/mol-model-formats/structure/property/bonds/struct_conn.ts
- scan all entities when looking for ``struct_conn`` entries
- solves PDB loading issue discussed in #486
> struct_conn parsing fix

- src/mol-canvas3d/canvas3d.ts
Hi,
This pull references issue #490
> only update camera state if manualReset is off

- src/mol-canvas3d/canvas3d.ts
> Deliver defaultAttribs to Passes constructor

- CHANGELOG.md
- examples/1bna_confal_pyramids.cif
- src/extensions/dnatco/confal-pyramids/behavior.ts
- src/extensions/dnatco/confal-pyramids/color.ts
- src/extensions/dnatco/confal-pyramids/property.ts
- src/extensions/dnatco/confal-pyramids/representation.ts
- src/extensions/dnatco/confal-pyramids/types.ts
- src/extensions/dnatco/confal-pyramids/util.ts
My original intention was to just add labels to Confal pyramids. In retrospect I realized that some of the naming used in the code was quite misleading so I tried to improve upon that as well.
> Add labels for Confal pyramids

- CHANGELOG.md
- src/mol-model-props/common/custom-element-property.ts
- can't check data availabilty in isApplicable because it is obtained on demand
> fix CustomElementProperty coloring

- CHANGELOG.md
- src/mol-canvas3d/passes/draw.ts
- src/mol-canvas3d/passes/fxaa.ts
- src/mol-canvas3d/passes/marking.ts
- src/mol-canvas3d/passes/multi-sample.ts
- src/mol-canvas3d/passes/postprocessing.ts
- src/mol-canvas3d/passes/smaa.ts
- src/mol-geo/geometry/texture-mesh/color-smoothing.ts
- src/mol-gl/compute/grid3d.ts
- src/mol-gl/compute/histogram-pyramid/reduction.ts
- src/mol-gl/compute/histogram-pyramid/sum.ts
- src/mol-gl/compute/marching-cubes/active-voxels.ts
- src/mol-gl/compute/marching-cubes/isosurface.ts
- src/mol-gl/compute/util.ts
- src/mol-gl/renderer.ts
- src/mol-gl/scene.ts
- src/mol-gl/webgl/context.ts
- src/mol-gl/webgl/render-item.ts
- src/mol-gl/webgl/state.ts
- src/mol-math/geometry/gaussian-density/gpu.ts
- Reduce number of webgl state changes
- Add ``viewport`` and ``scissor`` to state object
- Add ``hasOpaque`` to scene object
- Handle edge cases where some renderables would not get (correctly) rendered
- Fix text background rendering for opaque text
- Fix helper scenes not shown when rendering directly to draw target
> Webgl state

- CHANGELOG.md
- src/mol-canvas3d/passes/wboit.ts
- src/mol-gl/shader/cylinders.frag.ts
- src/mol-gl/shader/spheres.frag.ts
- src/mol-plugin/config.ts
- src/mol-plugin/features.ts
> add missing depth renderbuffer to wboit pass

- CHANGELOG.md
- src/mol-plugin/behavior/dynamic/volume-streaming/behavior.ts
- src/mol-plugin/behavior/dynamic/volume-streaming/transformers.ts
> Change EM Volume Streaming default Auto

- CHANGELOG.md
- src/mol-math/geometry/symmetry-operator.ts
- src/mol-model-formats/structure/property/bonds/index-pair.ts
- src/mol-model/structure/query/context.ts
- src/mol-model/structure/structure/properties.ts
- src/mol-model/structure/structure/unit/bonds/inter-compute.ts
- src/mol-model/structure/structure/unit/bonds/intra-compute.ts
- src/mol-script/language/symbol-table/structure-query.ts
- src/mol-script/runtime/query/table.ts
- src/mol-script/script/mol-script/symbols.ts
- molql operatorKey
- index-pair operator prop
> add key to symmetry operator

- CHANGELOG.md
- src/mol-geo/geometry/overpaint-data.ts
- src/mol-geo/geometry/substance-data.ts
- src/mol-geo/geometry/transparency-data.ts
- src/mol-gl/renderable/schema.ts
- src/mol-gl/shader/chunks/assign-color-varying.glsl.ts
- src/mol-gl/shader/chunks/color-vert-params.glsl.ts
- src/mol-plugin-state/transforms/representation.ts
- src/mol-plugin/spec.ts
- src/mol-repr/representation.ts
- src/mol-repr/structure/complex-representation.ts
- src/mol-repr/structure/complex-visual.ts
- src/mol-repr/structure/units-representation.ts
- src/mol-repr/structure/units-visual.ts
- src/mol-repr/visual.ts
- src/mol-repr/volume/representation.ts
> add theme strength to 3d repr state

- src/mol-model/sequence/alignment/sequence.ts
- src/mol-model/structure/structure/util/superposition.ts
- src/mol-plugin-ui/sequence.tsx
- src/mol-plugin-ui/sequence/sequence.tsx
- src/mol-plugin-ui/structure/superposition.tsx
Change function and class access modifiers.
> change access modifiers

- CHANGELOG.md
- src/extensions/model-archive/quality-assessment/prop.ts
- src/mol-model/structure/model/properties/atomic/hierarchy.ts
- src/mol-model/structure/model/properties/utils/atomic-index.ts
> Fix QualityAssessment assignment

- CHANGELOG.md
- src/mol-plugin-ui/state/apply-action.tsx
Refresh params for state actions each time they are expanded. This allows dynamic params for root state actions.
> ApplyActionControl param handling

- CHANGELOG.md
- src/extensions/cellpack/model.ts
- src/mol-plugin-state/builder/structure/representation-preset.ts
- src/mol-plugin-state/manager/structure/component.ts
- src/mol-plugin/behavior/dynamic/selection/structure-focus-representation.ts
- src/mol-repr/structure/visual/bond-inter-unit-cylinder.ts
- src/mol-repr/structure/visual/bond-inter-unit-line.ts
- src/mol-repr/structure/visual/bond-intra-unit-cylinder.ts
- src/mol-repr/structure/visual/bond-intra-unit-line.ts
- src/mol-repr/structure/visual/element-cross.ts
- src/mol-repr/structure/visual/element-point.ts
- src/mol-repr/structure/visual/element-sphere.ts
- src/mol-repr/structure/visual/gaussian-density-volume.ts
- src/mol-repr/structure/visual/gaussian-surface-mesh.ts
- src/mol-repr/structure/visual/gaussian-surface-wireframe.ts
- src/mol-repr/structure/visual/molecular-surface-mesh.ts
- src/mol-repr/structure/visual/molecular-surface-wireframe.ts
- src/mol-repr/structure/visual/util/bond.ts
- src/mol-repr/structure/visual/util/common.ts
- src/mol-repr/structure/visual/util/element.ts
> Ability to show only polar hydrogens

- CHANGELOG.md
- src/mol-plugin-ui/controls/line-graph/line-graph-component.tsx
- src/mol-plugin-ui/controls/parameters.tsx
- src/mol-repr/volume/direct-volume.ts
- src/mol-util/param-definition.ts
> Show histogram in direct volume control point settings

- CHANGELOG.md
- src/mol-geo/geometry/cylinders/cylinders.ts
- src/mol-geo/geometry/spheres/spheres.ts
- src/mol-gl/renderable/cylinders.ts
- src/mol-gl/renderable/spheres.ts
- src/mol-gl/shader/cylinders.frag.ts
- src/mol-gl/shader/cylinders.vert.ts
- src/mol-gl/shader/spheres.frag.ts
> Solid impostors

- CHANGELOG.md
- src/mol-plugin-state/builder/structure/representation-preset.ts
- src/mol-plugin-state/manager/structure/component.ts
- src/mol-plugin/behavior/dynamic/selection/structure-focus-representation.ts
- src/mol-repr/structure/visual/bond-inter-unit-cylinder.ts
- src/mol-repr/structure/visual/bond-inter-unit-line.ts
- src/mol-repr/structure/visual/bond-intra-unit-cylinder.ts
- src/mol-repr/structure/visual/bond-intra-unit-line.ts
- src/mol-repr/structure/visual/element-cross.ts
- src/mol-repr/structure/visual/element-point.ts
- src/mol-repr/structure/visual/element-sphere.ts
- src/mol-repr/structure/visual/gaussian-density-volume.ts
- src/mol-repr/structure/visual/gaussian-surface-mesh.ts
- src/mol-repr/structure/visual/gaussian-surface-wireframe.ts
- src/mol-repr/structure/visual/molecular-surface-mesh.ts
- src/mol-repr/structure/visual/molecular-surface-wireframe.ts
- src/mol-repr/structure/visual/util/bond.ts
- src/mol-repr/structure/visual/util/common.ts
- src/mol-repr/structure/visual/util/element.ts
> tweak ignoreHydrogens non-polar handling

- src/extensions/meshes/mesh-extension.ts
- src/extensions/volumes-and-segmentations/entry-root.ts
> Volseg: Fixed not loading volume section from state

- CHANGELOG.md
- src/mol-plugin-ui/controls/color.tsx
- src/mol-plugin-ui/structure/volume.tsx
> Volume Quick Color Select Control

- CHANGELOG.md
- src/mol-geo/geometry/base.ts
- src/mol-model/structure/structure/structure.ts
- src/mol-model/structure/structure/unit.ts
- src/mol-plugin-ui/controls/color.tsx
- src/mol-plugin-ui/controls/parameters.tsx
- src/mol-repr/structure/representation/ball-and-stick.ts
- src/mol-repr/structure/representation/carbohydrate.ts
- src/mol-repr/structure/representation/ellipsoid.ts
- src/mol-repr/structure/representation/gaussian-surface.ts
- src/mol-repr/structure/representation/gaussian-volume.ts
- src/mol-repr/structure/representation/label.ts
- src/mol-repr/structure/representation/line.ts
- src/mol-repr/structure/representation/molecular-surface.ts
- src/mol-repr/structure/representation/orientation.ts
- src/mol-repr/structure/representation/point.ts
- src/mol-repr/structure/representation/spacefill.ts
- src/mol-util/color/color.ts
- Add `input type='color'` picker to `CombinedColorControl`
- Set `ParameterMappingControl` disabled when state is updating
- Performance tweaks
- Update clip `defines` only when changed
- Check for identity in structure/unit areEqual methods
- Avoid cloning of structure representation parameters
> Misc tweaks

- CHANGELOG.md
- src/mol-canvas3d/passes/draw.ts
- src/mol-canvas3d/passes/marking.ts
- src/mol-canvas3d/passes/pick.ts
- src/mol-gl/renderable/schema.ts
- src/mol-gl/renderer.ts
- src/mol-gl/shader/chunks/apply-marker-color.glsl.ts
- src/mol-gl/shader/chunks/common-frag-params.glsl.ts
- src/mol-gl/shader/direct-volume.frag.ts
- src/mol-gl/shader/marking/overlay.frag.ts
> support dim unmarked groups & marker edge strength

- CHANGELOG.md
- src/mol-plugin-state/manager/snapshots.ts
- src/mol-plugin-ui/skin/base/components/misc.scss
- src/mol-plugin-ui/skin/base/variables.scss
- src/mol-plugin-ui/state/snapshots.tsx
- src/mol-plugin/behavior/static/state.ts
- src/mol-plugin/state.ts
- src/mol-util/assets.ts
Not enabled by default since images are quite big compared most protein files. Tweaks and suggestions most welcome.
> state snapshot images

- CHANGELOG.md
- src/mol-canvas3d/helper/camera-helper.ts
> add axes camera-helper customization options

- src/apps/viewer/app.ts
- src/examples/alpha-orbitals/index.ts
- src/mol-canvas3d/canvas3d.ts
- src/mol-canvas3d/passes/pick.ts
- src/mol-gl/webgl/context.ts
- src/mol-gl/webgl/render-item.ts
- src/mol-gl/webgl/timer.ts
- src/mol-util/debug.ts
> add consoleStats, improve timer

- CHANGELOG.md
- package.json
- src/mol-repr/structure/visual/util/link.ts
> allow link cylinder/line `dashCount` set to '0'

- CHANGELOG.md
- src/apps/docking-viewer/viewport.tsx
- src/examples/lighting/index.ts
- src/extensions/cellpack/model.ts
- src/mol-canvas3d/passes/postprocessing.ts
- src/mol-gl/shader/outlines.frag.ts
- src/mol-gl/shader/postprocessing.frag.ts
- src/mol-gl/shader/ssao-blur.frag.ts
- src/mol-plugin-ui/structure/quick-styles.tsx
- src/mol-plugin/util/headless-screenshot.ts
> Post-processing improvements

- CHANGELOG.md
- src/mol-gl/renderer.ts
Avoid rendering of fully transparent renderables when using dpoit
> Dpoit avoid alpha 0 rendering

- CHANGELOG.md
- src/mol-canvas3d/helper/interaction-events.ts
- src/mol-plugin-ui/controls.tsx
- src/mol-plugin-ui/viewport.tsx
- src/mol-util/input/input-observer.ts
Only trigger `identify` when event originated from the canvas
> Marking improvements

- CHANGELOG.md
- src/examples/image-renderer/index.ts
- src/mol-util/data-source.ts
> Add setFSModule to fix WebPack builds

- src/apps/docking-viewer/viewport.tsx
- src/examples/lighting/index.ts
- src/extensions/cellpack/model.ts
- src/mol-canvas3d/passes/postprocessing.ts
- src/mol-gl/renderer.ts
- src/mol-gl/shader/ssao.frag.ts
- src/mol-plugin-ui/structure/quick-styles.tsx
- src/mol-plugin/util/headless-screenshot.ts
- src/mol-util/clip.ts
> add multi-scale ssao

- CHANGELOG.md
- src/mol-plugin-state/manager/structure/component.ts
- src/mol-plugin/state.ts
> PluginState.setSnapshot fix

- CHANGELOG.md
- src/extensions/geo-export/glb-exporter.ts
- src/extensions/geo-export/mesh-exporter.ts
- src/extensions/geo-export/obj-exporter.ts
- src/extensions/geo-export/stl-exporter.ts
- src/extensions/geo-export/usdz-exporter.ts
[support points & lines in glTF export](https://github.com/molstar/molstar/commit/03dba0bde7e3a282b60122a92713187d74b625cc)
> Geo export2

- CHANGELOG.md
- src/mol-model-formats/structure/pdb/atom-site.ts
- src/mol-model-formats/structure/pdb/to-cif.ts
Fix for issue raised in https://github.com/molstar/molstar/issues/816
> Fix Archive PDB assembly loading

- CHANGELOG.md
- src/mol-model/structure/structure/unit/bonds/inter-compute.ts
The previous version did the tests in ineffective order.
> optimize computeInterUnitBonds

- CHANGELOG.md
- src/mol-math/graph/int-adjacency-graph.ts
- src/mol-model-formats/structure/property/bonds/index-pair.ts
- src/mol-model/structure/structure/structure.ts
> Graph & bonds calc tweaks & fixes

- CHANGELOG.md
- src/mol-plugin-state/manager/structure/selection.ts
- src/mol-plugin/state.ts
Add snapshot support for structure selections. Off by default.
> add snapshot support for structure selections

- CHANGELOG.md
- package-lock.json
- package.json
- src/extensions/model-export/export.ts
> Model export name

- CHANGELOG.md
- src/mol-model-props/sequence/sifts-mapping.ts
> fix display issue with sifts mapping

- CHANGELOG.md
- src/mol-repr/structure/visual/element-point.ts
- src/mol-repr/structure/visual/element-sphere.ts
- src/mol-repr/structure/visual/util/element.ts
quick option to reduce number of elements to render
> add stride option to element sphere & point visuals

- CHANGELOG.md
- src/mol-math/linear-algebra/3d/euler.ts
- src/mol-math/linear-algebra/3d/mat4.ts
- src/mol-math/linear-algebra/3d/quat.ts
- src/mol-math/linear-algebra/_spec/euler.spec.ts
> add euler math primitive

- CHANGELOG.md
- src/extensions/geo-export/mesh-exporter.ts
- src/mol-geo/geometry/geometry.ts
- src/mol-geo/geometry/spheres/spheres-builder.ts
- src/mol-geo/geometry/spheres/spheres.ts
- src/mol-gl/_spec/gl.ts
- src/mol-gl/_spec/spheres.spec.ts
- src/mol-gl/renderable/spheres.ts
- src/mol-gl/shader/spheres.vert.ts
- src/mol-repr/structure/visual/element-sphere.ts
- src/mol-repr/structure/visual/polymer-backbone-sphere.ts
- derive mapping from VertexID
- pull position and group from texture
> reduce spheres geo memory usage

- CHANGELOG.md
- src/apps/viewer/app.ts
- src/apps/viewer/index.html
> ability to disable extension in the default viewer

- CHANGELOG.md
- src/mol-plugin-state/builder/structure/representation-preset.ts
- src/mol-plugin/state.ts
> fix updateFocusRepr

- CHANGELOG.md
- src/mol-model-formats/structure/mmcif.ts
- src/mol-plugin-state/transforms/model.ts
> Add optional CifFile to MmcifFormat.data

- CHANGELOG.md
- src/mol-plugin-ui/viewport/simple-settings.tsx
> hide right panel

- src/apps/viewer/app.ts
- src/apps/viewer/index.html
- src/extensions/rcsb/assembly-symmetry/behavior.ts
- src/extensions/rcsb/assembly-symmetry/prop.ts
- src/extensions/rcsb/assembly-symmetry/ui.tsx
I added options to customize RCSBAssemblySymmetry extension via plugin config items and possibility to retrieve data from PDBe API.
> Assembly Symmetry extension customization

- CHANGELOG.md
- src/mol-model-formats/structure/pdb/atom-site.ts
fix for #945 by creating serial label_seq_id for PDB files with ins code present
> fix handling of pdb files with insertion codes

- docs/extensions/mvs/README.md
- docs/extensions/mvs/molviewspec-v1-openapi-schema.json
> MVS: OpenApi schema in docs

- CHANGELOG.md
- src/mol-plugin/util/headless-screenshot.ts
I fixed label rendering in plugin mode (https://github.com/molstar/molstar/issues/1058).
> Fixed text rendering in headless mode

- CHANGELOG.md
- src/mol-plugin-state/transforms/volume.ts
Provide a state transformer to rotate/translate volumes in a similar manner to structures, like in superposition.
Closes #1055.
> VolumeTransform to rotate a volume, like TransformStructureConformation

- CHANGELOG.md
- src/mol-canvas3d/passes/postprocessing.ts
- src/mol-repr/structure/visual/gaussian-surface-mesh.ts
> Fix SSAO broken when `OES_texture_float_linear` is unavailable

- CHANGELOG.md
- src/mol-canvas3d/canvas3d.ts
- src/mol-canvas3d/passes/dpoit.ts
- src/mol-canvas3d/passes/draw.ts
- src/mol-plugin/util/headless-screenshot.ts
Fix for #1058, and follow-up to #1068
> Fix transparency rendering fallback

- CHANGELOG.md
- src/mol-gl/shader/ssao-blur.frag.ts
- src/mol-gl/shader/ssao.frag.ts
See #1082, thanks @corredD for the patch and thanks @giagitom for identifying the issue.
> Fix SSAO artifacts (@corredD, #1082)

- CHANGELOG.md
- src/mol-gl/shader/chunks/assign-material-color.glsl.ts
> fix bumpiness artifact

- CHANGELOG.md
- package.json
- src/apps/viewer/app.ts
- src/mol-plugin-state/transforms/data.ts
Created DecompressGzip transformer to be able to load map.gz files correctly:
Root
└Download
└Decompress GZIP
└Parse CCP4
> Decompress gzip volume

- CHANGELOG.md
- src/mol-plugin-ui/structure/quick-styles.tsx
> Adjust quick styles panel

- CHANGELOG.md
- src/mol-canvas3d/camera/transition.ts
Interpolate camera rotation instead of just position
Before:
https://github.com/molstar/molstar/assets/21145776/c401545a-b229-4554-9ba2-1a9b8c2f4c4d
After:
https://github.com/molstar/molstar/assets/21145776/7bd6a0b6-5ebd-485e-93cd-6c9302f9b02e
> Improve camera interpolation

- CHANGELOG.md
- src/apps/mesoscale-explorer/behavior/camera.ts
- src/apps/mesoscale-explorer/behavior/select.ts
- src/apps/mesoscale-explorer/ui/panels.tsx
Mouse left click on label with snapshot key load the snapshot. Important feature for navigating a tour directly from the 3d view. 
Mouse hover label with protein name highlight entities with the same name.
> Mesoscale Explorer mouse select behavior

- CHANGELOG.md
- src/mol-gl/shader/cylinders.frag.ts
PR for cleaner solidInterior transparent cylinders. mentioned in #1124
- [ x] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [ x] Updated headers of modified files
> Clean solid interior transparent cylinders

- src/mol-gl/shader/chunks/apply-light-color.glsl.ts
- clamp metalness & roughness to look better
fix for #1168
> cel-shading artifacts

- CHANGELOG.md
- src/mol-plugin-ui/plugin.tsx
- src/mol-plugin-ui/spec.ts
> Ability to customize snapshot description component

- CHANGELOG.md
- src/apps/mesoscale-explorer/app.ts
- src/apps/mesoscale-explorer/behavior/select.ts
- src/apps/mesoscale-explorer/data/state.ts
- src/apps/mesoscale-explorer/style.scss
- src/apps/mesoscale-explorer/ui/entities.tsx
- src/apps/mesoscale-explorer/ui/panels.tsx
- src/mol-plugin-ui/controls/icons.tsx
- src/mol-plugin-ui/skin/base/components/viewport.scss
Custom ViewportSnapshotDescription with custom MarkdowAnchor  :
- `#` other snapshots with a given key `[...](#key)`
- `i` highlight a protein with a given NAME `[...](iNAME)`
- `g` highlight a group with a given group type and group name `[...](ggrouptype.groupname)`
- `h` URLs with a given link `[...](http...)`
Snapshot description panel window size and text can be resized and hidden with new icons.
> Mesoscale Explorer Snapshot Description

- src/apps/mesoscale-explorer/app.ts
Use the tours.json file in examples/ folder of the website hosting the app (e.g. molstar.org/me). 
see [PR #11](https://github.com/molstar/molstar.github.io/pull/11).
> file holdng the molx available tour.

- CHANGELOG.md
- package.json
- src/mol-canvas3d/controls/trackball.ts
- src/mol-util/input/input-observer.ts
Address #1190.
@dsehnal I took a stab at it. What do you think, and do you have suggestions for improvements? My other PR #1191 adds a test page that creates a grid of four Canvas3Ds which you could use to test this out. If you think this is a good solution direction, I will check off the points below.
> Improve pinch event

- CHANGELOG.md
- src/mol-repr/structure/visual/bond-inter-unit-cylinder.ts
- src/mol-repr/structure/visual/bond-inter-unit-line.ts
- src/mol-repr/structure/visual/bond-intra-unit-cylinder.ts
- src/mol-repr/structure/visual/bond-intra-unit-line.ts
- src/mol-repr/structure/visual/util/link.ts
- src/tests/browser/index.html
- src/tests/browser/render-structure-grid.ts
- webpack.config.js
Address #1188.
@arose This is not the prettiest solution because it adds an ad-hoc parameter to LinkBuilderProps, but it does work. If you are happy with it I will check off the points below.
> Add unadjusted position for aromatic link dashes

- src/apps/mesoscale-explorer/ui/states.tsx
Loading tours example from the menu was raising a node error that didnt happen with drag/drop. 
LoadURL nnow behave like OpenState.
> Load URL now behave like drag/drop. 

- src/apps/mesoscale-explorer/ui/states.tsx
simple change for the new docs URL
> Update states.tsx docs url

- CHANGELOG.md
- src/mol-canvas3d/passes/postprocessing.ts
> use texture linear filter for SSAO when available

- CHANGELOG.md
- src/extensions/mp4-export/encoder.ts
- src/mol-canvas3d/passes/image.ts
- src/mol-plugin-state/manager/snapshots.ts
- src/mol-plugin-ui/controls/screenshot.tsx
- src/mol-plugin/headless-plugin-context.ts
- src/mol-plugin/util/headless-screenshot.ts
- src/mol-plugin/util/viewport-screenshot.ts
Wrap screenshot & image generation in a `Task`. This will allow observing multi-step image generation in the future.
> wrap screenshot & image generation in a Task

- CHANGELOG.md
- docs/docs/misc/interesting-pdb-entries.md
- src/mol-model-props/computed/secondary-structure.ts
- src/mol-model-props/computed/secondary-structure/dssp.ts
- src/mol-model-props/computed/secondary-structure/zhang-skolnik.ts
- src/mol-model/structure/model/model.ts
- src/mol-model/structure/model/types.ts
- src/mol-model/structure/structure/unit/bonds/intra-compute.ts
- src/mol-plugin-state/builder/structure/representation-preset.ts
- src/mol-repr/structure/visual/polymer-trace-mesh.ts
- src/mol-repr/structure/visual/util/polymer/trace-iterator.ts
- Add Zhang-Skolnick secondary-structure assignment method which handles coarse-grained models (#49)
- Calculate bonds for coarse-grained models
> improve coarse-grained models handling

- src/apps/mesoscale-explorer/embedded.html
- src/apps/mesoscale-explorer/index.html
- src/apps/mesoscale-explorer/ui/states.tsx
Add a embedded.html example that relate to https://github.com/molstar/me-docs/blob/main/docs/embedding.md
Add a timer in LoadURL to reproduce loading time
Add a default guided tour (machinery of life) when starting the viewer with no parameters.
> PR for Revision

- CHANGELOG.md
- src/mol-plugin-ui/skin/base/components/sequence.scss
Adjust cursor and font color of unmodeled sequence positions. Works better for me for the default theme.
> Sequence Panel: Improve visuals of unmodeled sequence positions

- CHANGELOG.md
- src/mol-model-formats/structure/pdb/atom-site.ts
- src/mol-model-formats/structure/pdb/to-cif.ts
Fix handling of PDB files that have chains with same id separated by TER record.
Fixes #1245.
> Fix handling of PDB files

- CHANGELOG.md
- src/apps/mesoscale-explorer/ui/states.tsx
- src/mol-canvas3d/passes/draw.ts
- src/mol-canvas3d/passes/postprocessing.ts
- src/mol-canvas3d/passes/shadow.ts
- src/mol-gl/renderer.ts
- src/mol-gl/shader/shadows.frag.ts
> fix shadows with multiple lights

- src/apps/mesoscale-explorer/ui/states.tsx
> Revert "fix preset coloring in ME"

- CHANGELOG.md
- src/apps/mesoscale-explorer/data/cellpack/preset.ts
- src/apps/mesoscale-explorer/data/mmcif/preset.ts
- src/apps/mesoscale-explorer/data/petworld/preset.ts
- src/apps/mesoscale-explorer/data/state.ts
- src/apps/mesoscale-explorer/ui/entities.tsx
- src/apps/mesoscale-explorer/ui/states.tsx
Fixes for coloring/styling in ME
see #1277
> ME: color and style fixes

- CHANGELOG.md
- src/apps/mesoscale-explorer/app.ts
- src/apps/mesoscale-explorer/index.html
- src/apps/viewer/app.ts
- src/apps/viewer/index.html
- src/mol-canvas3d/canvas3d.ts
- src/mol-plugin/config.ts
- src/mol-plugin/context.ts
- src/mol-util/browser.ts
Addresses https://github.com/molstar/molstar/issues/1279
> add resolutionMode.auto

- docs/docs/misc/exporting-components.md
- docs/mkdocs.yml
- package.json
Add a doc page to describe how to export components
> Add doc page to describe how to access component data

- src/mol-canvas3d/passes/draw.ts
- src/mol-canvas3d/passes/illumination.ts
- src/mol-canvas3d/passes/pick.ts
- src/mol-canvas3d/passes/tracing.ts
- src/mol-gl/renderer.ts
- src/mol-gl/shader/chunks/apply-fog.glsl.ts
- src/mol-gl/shader/direct-volume.frag.ts
Fix direct-volume for dpoit with fog off and transparent background on (#1286)
Fix missing pre-multiplied alpha for blended & wboit with no fog (#1284)
> Transparency related fixes

- CHANGELOG.md
- src/mol-gl/shader/chunks/apply-light-color.glsl.ts
- src/mol-gl/shader/chunks/assign-material-color.glsl.ts
- src/mol-gl/shader/chunks/check-transparency.glsl.ts
- src/mol-gl/shader/chunks/common-frag-params.glsl.ts
- src/mol-gl/shader/chunks/common.glsl.ts
- src/mol-gl/shader/cylinders.frag.ts
- src/mol-gl/shader/mesh.frag.ts
- src/mol-gl/shader/spheres.frag.ts
fix backfaces visible using blended transparency on impostors - fixes #1285
> fix backfaces visible using blended transparency on impostors

- CHANGELOG.md
- src/mol-plugin-ui/skin/base/components/sequence.scss
> fix sequence view in Safari

- CHANGELOG.md
- package.json
- src/examples/glb-export/index.ts
- add example [glb-export](https://github.com/dirkarnez/molstar/tree/master/src/examples/glb-export)
> - add glb export example

- CHANGELOG.md
- src/mol-canvas3d/canvas3d.ts
> Set fenceSync to null after deleteSync.

- CHANGELOG.md
- src/mol-geo/geometry/mesh/builder/tube.ts
- src/mol-repr/structure/visual/util/polymer/trace-iterator.ts
- Fix single residue tubular helices not showing up
- Enable rounded caps on single residue tubular helices
> Inprove tubular helices

- CHANGELOG.md
- src/mol-plugin-state/manager/snapshots.ts
> PluginStateSnapshotManager.syncCurrent fix

- package-lock.json
- package.json
- src/mol-plugin-ui/state/tree.tsx
- src/mol-plugin/util/substructure-parent-helper.ts
- src/mol-state/state/selection.ts
- src/mol-state/tree/immutable.ts
> update to immutable-js 5

- CHANGELOG.md
- src/mol-util/browser.ts
> Fix iOS check

- CHANGELOG.md
- src/mol-canvas3d/passes/illumination.ts
- src/mol-gl/shader/illumination/compose.frag.ts
> Fix outlines on transparent background using illuminartion mode

- CHANGELOG.md
- docs/docs/plugin/transforms/custom-conformation.md
- docs/mkdocs.yml
- src/mol-model/structure/model/model.ts
- src/mol-plugin-state/transforms/model.ts
Adds new `ModelWithCoordinates` transform that allows modifying existing model coordinates.
> Add ModelWithCoordinates transform

- CHANGELOG.md
- package.json
By loosening `peerDependencies`
> Support React 19

- CHANGELOG.md
- src/mol-repr/structure/visual/util/polymer.ts
Fix marking of consecutive gap elements (#876)
> fix marking of consecutive gap elements

- CHANGELOG.md
- src/tests/browser/marching-cubes.ts
- src/tests/browser/render-lines.ts
- src/tests/browser/render-mesh.ts
- src/tests/browser/render-shape.ts
- src/tests/browser/render-spheres.ts
- src/tests/browser/render-structure-grid.ts
- src/tests/browser/render-structure.ts
- src/tests/browser/render-text.ts
> wip, fix handle resize

- CHANGELOG.md
- src/mol-geo/geometry/direct-volume/direct-volume.ts
- src/mol-gl/compute/marching-cubes/active-voxels.ts
- src/mol-gl/compute/marching-cubes/isosurface.ts
- src/mol-gl/shader/marching-cubes/active-voxels.frag.ts
- src/mol-gl/shader/marching-cubes/isosurface.frag.ts
- src/mol-gl/webgl/texture.ts
- src/mol-model/custom-property.ts
- src/mol-repr/structure/visual/gaussian-density-volume.ts
- src/mol-repr/volume/direct-volume.ts
- src/mol-repr/volume/isosurface.ts
- src/mol-repr/volume/util.ts
- src/mol-util/number-conversion.ts
- direct-volume rendering
- GPU isosurface extraction
> Support float and half-float data type

- CHANGELOG.md
- src/mol-repr/structure/visual/polymer-trace-mesh.ts
- src/mol-repr/structure/visual/util/polymer/trace-iterator.ts
> Fix tubular helices issue

- CHANGELOG.md
- src/mol-model/location.ts
- src/mol-model/volume/volume.ts
- src/mol-repr/volume/dot.ts
- src/mol-repr/volume/registry.ts
- src/mol-repr/volume/representation.ts
- src/mol-repr/volume/util.ts
- src/mol-theme/size.ts
- src/mol-theme/size/volume-value.ts
Add volume dot representation and volume-value size theme
> add volume dot representation

- CHANGELOG.md
- src/examples/basic-wrapper/custom-theme.ts
- src/extensions/assembly-symmetry/color.ts
- src/extensions/dnatco/confal-pyramids/color.ts
- src/extensions/dnatco/ntc-tube/color.ts
- src/extensions/model-archive/quality-assessment/color/plddt.ts
- src/extensions/model-archive/quality-assessment/color/qmean.ts
- src/extensions/mvs/components/multilayer-color-theme.ts
- src/extensions/pdbe/structure-quality-report/color.ts
- src/extensions/rcsb/validation-report/color/density-fit.ts
- src/extensions/rcsb/validation-report/color/geometry-quality.ts
- src/extensions/rcsb/validation-report/color/random-coil-index.ts
- src/extensions/sb-ncbr/partial-charges/color.ts
- src/mol-model-props/computed/themes/accessible-surface-area.ts
- src/mol-model-props/computed/themes/interaction-type.ts
- src/mol-model-props/integrative/cross-link-restraint/color.ts
- src/mol-model-props/sequence/themes/sifts-mapping.ts
- src/mol-repr/representation.ts
> Remove static uses of `ColorTheme` and `SizeTheme` fields

- CHANGELOG.md
- src/examples/ihm-restraints/index.tsx
- src/extensions/mvs/load.ts
- src/mol-model-formats/structure/basic/coarse.ts
- src/mol-model/structure/model/properties/coarse/hierarchy.ts
- src/mol-model/structure/model/properties/utils/coarse-index.ts
- src/mol-plugin-ui/controls.tsx
> I/HM Example Improvements

- CHANGELOG.md
- src/examples/ihm-restraints/index.tsx
> ihm-restraints example: show entity labels

- CHANGELOG.md
- src/mol-plugin-state/manager/structure/measurement.ts
- src/mol-plugin-state/transforms/model.ts
> Use StructureElement.Bundle for measurements

- CHANGELOG.md
- src/extensions/mvs/tree/mvs/_spec/mvs-builder.spec.ts
- src/extensions/mvs/tree/mvs/mvs-builder.ts
Fix https://github.com/molstar/mol-view-spec/issues/58
> MVS: Fix state builder for volumes

- CHANGELOG.md
- src/apps/viewer/app.ts
> Fix Viewer.loadTrajectory

- CHANGELOG.md
- src/mol-model-formats/structure/mmcif.ts
> Fix StructConn.residueCantorPairs

- CHANGELOG.md
- src/mol-state/transformer.ts
> No error in Transformer.create

- CHANGELOG.md
- src/mol-repr/util.ts
adjust max resolution for auto quality (#1501)
> adjust max resolution for auto quality

- CHANGELOG.md
- src/mol-canvas3d/canvas3d.ts
- src/mol-gl/webgl/context.ts
https://github.com/molstar/molstar/pull/1520 introduced a bug in MP4 export. This should fix it.
> Fix camera interpolation during animation export

- CHANGELOG.md
- src/examples/interactions/index.tsx
- src/extensions/interactions/model.ts
- src/extensions/interactions/visuals.ts
Different software uses either `salt-bridge` or `ionic`. Kept the latter.
> Interactions extension: remove salt bridge interaction kind

- CHANGELOG.md
- src/mol-gl/compute/marching-cubes/isosurface.ts
- src/mol-gl/shader/marching-cubes/isosurface.frag.ts
- src/mol-math/linear-algebra/3d/mat3.ts
> Fix isosurface compute shader normals when transformation matrix is applied to volume 

- src/mol-canvas3d/camera.ts
- src/mol-canvas3d/camera/stereo.ts
- src/mol-canvas3d/passes/background.ts
- src/mol-gl/renderable/schema.ts
- src/mol-gl/renderer.ts
- src/mol-gl/shader/cylinders.vert.ts
- src/mol-gl/shader/spheres.frag.ts
- src/mol-gl/shader/spheres.vert.ts
- src/mol-gl/shader/text.vert.ts
- src/mol-math/linear-algebra/3d/mat4.ts
Add head rotation support
- handle skybox (follow head rotation)
- handle sphere (can't use function for exact sphere projection to get bounds, approximate) & text billboards (subtract head rotation)
Fix scale issues in cylinders & spheres shaders
Preparatory PR for WebXR support.
> Add head rotation support

- CHANGELOG.md
- src/apps/mvs-stories/context.ts
- src/apps/mvs-stories/elements/viewer.tsx
- src/apps/mvs-stories/index.html
- src/apps/mvs-stories/index.tsx
- src/examples/mvs-stories/index.html
- src/extensions/mvs/components/formats.ts
> MVS Stories: Add "Download MVS State" link

- src/mol-canvas3d/canvas3d.ts
- src/mol-canvas3d/helper/interaction-events.ts
- src/mol-canvas3d/helper/pick-helper.ts
- src/mol-canvas3d/helper/ray-helper.ts
- src/mol-canvas3d/passes/hi-z.ts
- src/mol-canvas3d/passes/pick.ts
- src/mol-gl/webgl/buffer.ts
- src/mol-gl/webgl/context.ts
- src/mol-gl/webgl/resources.ts
- src/mol-gl/webgl/texture.ts
- mark pick-helper dirty when async pick failed
- add pixel-pack buffer wrapper
- recover pixel-pack buffer after context loss (pick buffer, hi-z pass)
> fix async buffer issues

- src/extensions/mvs/tree/generic/field-schema.ts
> another io-ts import fix

- CHANGELOG.md
- src/extensions/mvs/camera.ts
- src/mol-canvas3d/canvas3d.ts
> MVS canvas molstar_postprocessing

- src/mol-canvas3d/passes/shadow.ts
- src/mol-gl/shader/shadows.frag.ts
fix the shadow shader to work on both eye
> fix shadow

- src/extensions/mvs/helpers/animation.ts
- src/extensions/mvs/load.ts
- src/mol-data/util/hash-functions.ts
- src/mol-state/transform.ts
Misc small improvements to the MVS animation code
> MVS animation improvements

- docs/docs/plugin/managers/markdown-extensions.md
- src/mol-plugin-state/manager/focus-camera/focus-object.ts
- src/mol-plugin-state/manager/markdown-extensions.ts
- src/mol-state/state/selection.ts
@corredD this should fix the error when focusing on transformed structure
> Fix Markdown Commands query focus

- scripts/build.mjs
- src/mol-util/produce.ts
> fix mutative use & assign NODE_ENV=production for prd builds

- src/mol-plugin-ui/sequence/sequence.tsx
Minor changes to the previous PR https://github.com/molstar/molstar/pull/1611 (allow passing theme props along with provider)
> Sequence color 2

- CHANGELOG.md
- src/servers/model/config.ts
- src/servers/model/server.ts
- src/servers/volume/config.ts
- src/servers/volume/server.ts
This will allow to optionally add (from configuration) a robots.txt file to the ModelServer.
> Add robots.txt to ModelServer

- CHANGELOG.md
- src/mol-plugin/util/viewport-screenshot.ts
> Fix screenshot animation loop handling

- package-lock.json
- package.json
reduces test runtime to ~1s (on M4 mac)
> use esbuild jest transformer

- src/mol-canvas3d/canvas3d.ts
- src/mol-geo/geometry/base.ts
- src/mol-gl/render-object.ts
- src/mol-gl/renderable/cylinders.ts
- src/mol-gl/renderable/direct-volume.ts
- src/mol-gl/renderable/image.ts
- src/mol-gl/renderable/lines.ts
- src/mol-gl/renderable/mesh.ts
- src/mol-gl/renderable/points.ts
- src/mol-gl/renderable/schema.ts
- src/mol-gl/renderable/spheres.ts
- src/mol-gl/renderable/text.ts
- src/mol-gl/renderable/texture-mesh.ts
- src/mol-gl/renderer.ts
- src/mol-gl/scene.ts
> global defines
