molstar/molstar

- src/mol-plugin/ui/controls/parameters.tsx
Switched the styling from option tag to the select tag. Option tag has limited styling and the linear-gradient property doesn't work on it.
> fixed lingrad

- src/mol-io/common/binary-cif/array-encoder.ts
Fix for #15 - use `numSteps - 1` during IntervalQuantization.
> fixes upper bound in interval quantization encoding

- package-lock.json
- src/servers/model/CHANGELOG.md
- src/servers/model/server/api-web.ts
- src/servers/model/server/api.ts
- src/servers/model/server/jobs.ts
- src/servers/model/server/query.ts
- src/servers/model/version.ts
- adds `transform` parameter to (single) ModelServer queries that will be applied to coordinates in `_atom_site`
- honors rest of query normally
- e.g. useful to select a binding site and superimpose it onto a 2nd binding site if alignment was determined externally
> Add transform functionality to ModelServer

- src/cli/chem-comp-dict/create-table.ts
- src/mol-model-formats/structure/property/atoms/chem_comp.ts
Previously, I ignored protonation variants when creating the chem_comp_atom.bcif. 
This PR fixes this bug. Code is analogous to the handling of variants in the context of chem_comp_bond data.
Thank you!
> create-table: add protonation variants to cca.bcif

- src/extensions/g3d/model.ts
add chromosome and region query for g3d format with examples below.
show struct from chr7:
```js
components.apply(StateTransforms.Model.StructureSelectionFromExpression, { expression: g3dChromosomeQuery('chr7'), label: 'chr7' })
.apply(StateTransforms.Representation.StructureRepresentation3D, reprChrom);
```
show struct from chr7:2000000-7000000:
```js
components.apply(StateTransforms.Model.StructureSelectionFromExpression, { expression: g3dRegionQuery('chr7', 2000000, 7000000), label: 'chr7:2000000-7000000' })
.apply(StateTransforms.Representation.StructureRepresentation3D, reprRegion);
```
> Add chromosome and region query for g3d format

- src/mol-io/writer/mol/encoder.ts
- src/mol-io/writer/mol2/encoder.ts
- src/servers/model/CHANGELOG.md
- src/servers/model/version.ts
- `bondMap` is undefined if metal ions are requested
- this PR ensures that those cases are handled gracefully and SDF/MOL/MOL2 files without bond information are returned
> handle metal ions correctly for ModelServer ligand export

- src/mol-io/writer/mol/encoder.ts
- src/mol-io/writer/mol2/encoder.ts
- src/servers/model/server/api-web-multiple.ts
- src/servers/model/server/api-web.ts
- src/servers/model/server/api.ts
- src/servers/model/server/jobs.ts
- adds functionality to specify filenames for download via ModelServer
- as a drive-by (4676ad8): mol/mol2 writing would fail if `params` category is undefined (e.g. if no atom_site properties are specified at all for a query)
A use-case lies in exporting multiple ligands from a structure, currently all files will be generically named `1pdb_ligand.ext`.
> ModelServer: filename parameter

- package-lock.json
- package.json
- src/apps/docking-viewer/index.ts
- src/apps/viewer/index.ts
- src/cli/state-docs/index.ts
- src/examples/alpha-orbitals/index.ts
- src/examples/basic-wrapper/index.ts
- src/examples/lighting/index.ts
- src/examples/proteopedia-wrapper/index.ts
- src/examples/proteopedia-wrapper/ui/controls.tsx
- src/mol-plugin-ui/base.tsx
- src/mol-plugin-ui/context.ts
- src/mol-plugin-ui/controls/parameters.tsx
- src/mol-plugin-ui/index.ts
- src/mol-plugin-ui/plugin.tsx
- src/mol-plugin-ui/spec.ts
- src/mol-plugin-ui/viewport/simple-settings.tsx
- src/mol-plugin/context.ts
- src/mol-plugin/layout.ts
- src/mol-plugin/spec.ts
- src/mol-plugin/util/toast.ts
Moves all React dependencies from ``mol-plugin`` to ``mol-plugin-ui`` by introducing ``PluginUIContext``.
> Move part of PluginContext to mol-plugin-ui

- src/mol-canvas3d/util.ts
FIX issue #147 CSS transform:scale cause molstar canvas to have incorrect size
When CSS transform is used e.g.: scale(0.5);transform-origin:top left;width:200% molstar canvas is broken. 
The introduced fix uses HTMLElement offsetWidth/offsetHeight properties containing correct size of element when css transform:scale is used.
> FIX issue #147 CSS transform:scale cause molstar canvas to have incorrect size

- src/mol-util/zip/deflate.ts
The `deflate` function sometimes reports partial progress where the current value is larger than the max value, such as "Deflating... [417630611/252028364]". This usually happens when exporting a large mesh such as 1RB8. This PR fixes the issue by using the correct current value.
> Fix incorrect deflate progress

- src/extensions/geo-export/controls.ts
- src/extensions/geo-export/export.ts
This PR adds support for exporting TextureMesh by retrieving data from the GPU, as suggested by @arose over emails.
You can try the demo here https://stanford.edu/~sukolsak/molstar/ It should be able to export Gaussian surfaces now.
(#28)
> Add TextureMesh export support

- CHANGELOG.md
- src/extensions/geo-export/controls.ts
- src/extensions/geo-export/glb-exporter.ts
- src/extensions/geo-export/mesh-exporter.ts
- src/extensions/geo-export/obj-exporter.ts
- src/extensions/geo-export/render-object-exporter.ts
- src/extensions/geo-export/stl-exporter.ts
- src/extensions/geo-export/ui.tsx
- src/mol-geo/geometry/size-data.ts
- src/mol-io/common/ascii.ts
This PR adds glTF (GLB) and STL support to the ``geo-export`` extension. I think users will find [these](https://twitter.com/FalconieriV/status/1197501082597036035) [formats](https://twitter.com/bradyajohnston/status/1387989340060459015) useful. As always, you can try it at https://stanford.edu/~sukolsak/molstar/
Let me know if this PR is too large. I can break it into smaller PRs.
Notes:
- The text for the GLB format option is "GLB". Blender uses "glTF Binary (.glb)". Let me know what you prefer.
- When I export some model such as 1TQN, some normal vectors are not normalized. Some vector has the magnitude as low as 0.2. I don't know why. If I don't normalize them, the exported file is still displayed in all the glTF viewers that I've tried. But …
> GLB and STL export

- src/mol-geo/geometry/mesh/builder/sheet.ts
This PR makes the normal vectors in sheet caps unit vectors while also using one fewer statement.
Part of #175.
> Fix normals in sheet caps

- src/extensions/geo-export/glb-exporter.ts
- src/extensions/geo-export/mesh-exporter.ts
- src/extensions/geo-export/obj-exporter.ts
- src/extensions/geo-export/stl-exporter.ts
- src/mol-geo/geometry/mesh/color-smoothing.ts
#173 will add new `dColorType` values: "volume" | "volumeInstance". This PR adds support for them in the geometry exporters and resolves #184.
Most changes in this PR are moving the instance loop inside `addMeshWithColors` so that we can call `getTrilinearlyInterpolated` just once. This might also facilitate a potential plan to use the instancing feature in GLTF in the future.
Since vertex coloring [doesn't](https://gamedev.stackexchange.com/questions/21303/how-can-i-include-vertex-color-information-in-obj-files) [seem](https://blender.stackexchange.com/questions/90890/how-to-display-and-use-vertex-color-from-obj-model) to be officially supported in OBJ, exporting raw volume colors can create hundreds of thousands of colors in the MTL file and make some 3D software like Blender take …
> Geometry export: support volume & volumeInstance color types

- src/extensions/geo-export/glb-exporter.ts
- src/extensions/geo-export/mesh-exporter.ts
- src/extensions/geo-export/obj-exporter.ts
- src/extensions/geo-export/stl-exporter.ts
- src/mol-repr/structure/visual/gaussian-surface-mesh.ts
- src/mol-repr/structure/visual/molecular-surface-mesh.ts
glTF/GLB supports [instancing](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#instantiation); The same mesh can be used by multiple nodes, which can have different transformations. The same vertex/normal/index/color buffers can also be used by multiple meshes. This PR tries to reuse meshes and buffers whenever possible.
- Use the same vertex/normal/index buffers for all instances if all instances have the same geometry. That is, the `GraphicsRenderObject`'s type is `mesh` or `texture-mesh`.
- Use the same color buffer for all instances if the color type is not one of the `*Instance` color types and per-group transparency is not used.
- If both conditions are true, use the same `mesh` object for all instances.
Exporting models with many instances such as 1RB8, 6CO8, …
> Geometry export: use instancing in GLB

- src/mol-canvas3d/passes/smaa.ts
`typeof` always returns a string.
> Fix HTMLImageElement check for SMAA

- src/extensions/geo-export/controls.ts
- src/extensions/geo-export/glb-exporter.ts
- src/mol-gl/renderer.ts
Add a material to the glTF/GLB exporter based on the global renderer style, as @arose suggested.
I can't adjust the light intensity, roughness, etc. when choosing the "Custom" lighting mode in the viewer. Is this intentional?
> Geometry export: add material to GLB

- src/extensions/anvil/algorithm.ts
- src/extensions/anvil/prop.ts
- src/extensions/anvil/representation.ts
- src/mol-model-props/computed/accessible-surface-area/shrake-rupley.ts
- src/mol-model-props/computed/accessible-surface-area/shrake-rupley/area.ts
- src/mol-model-props/computed/accessible-surface-area/shrake-rupley/common.ts
- src/mol-model-props/computed/accessible-surface-area/shrake-rupley/radii.ts
Provides a number of fixes for issues with the ANVIL implementation, which predicts the location of the membrane layer.
- new alpha-only parameter for ASA calculation which is faster and provides values closer to the NACCESS configuration used in the original ANVIL code
- fixes a typo which confused threonine and tryptophan, leading to egregiously bad predictions in some cases
- implements routine to adjust the thickness of the membrane layer
- better way to determine the radius of membrane layer
- add some status updates
- removes remnants of the deleted sphere visuals
- fix for ASA calculation/visual issues - #132 
**Question**
`Mat3.directionTransform` might fail to invert if a structure is oriented exactly along an axis (happens e.g. for 5CBG). Given that, I've changed the code to use …
> ANVIL fixes

- src/extensions/geo-export/mesh-exporter.ts
Automatically adjust the quality of sphere/cylinder meshes, as @arose suggested. This should help reduce the exported file size when using spacefill with large models.
> Geometry export: auto adjust quality of sphere/cylinder meshes

- src/extensions/geo-export/mesh-exporter.ts
- src/mol-repr/structure/visual/gaussian-surface-mesh.ts
- src/mol-repr/structure/visual/molecular-surface-mesh.ts
#199 will add a new property to mesh render-objects which holds some original data after applying uniformTriangleGroup to a mesh. This PR uses that property to export meshes and also reverts bc998ab. This should make the export file size the same for WebGL1 and WebGL2. For example, 1RB8.glb is currently 4.7 MB in Safari and 1.6 MB in Chrome. With this PR, it will be 1.6 MB in both browsers.
> Geometry export: use original mesh data

- src/extensions/geo-export/mesh-exporter.ts
- src/mol-geo/geometry/mesh/mesh.ts
- src/mol-gl/renderable/mesh.ts
- src/mol-gl/renderable/schema.ts
- src/mol-repr/structure/visual/gaussian-surface-mesh.ts
- src/mol-repr/structure/visual/molecular-surface-mesh.ts
@sukolsak This adds a new property to mesh render-objects which holds some original data after applying uniformTriangleGroup to a mesh. That original data can be used to do the export and revert the change to the uniformTriangleGroup calls (bc998ab328c5a2063aa5986d1e5bb03b1d89b608). With that the file size should be the same for webgl1 and 2.
```ts
const ro = renderObjects[i];
if ('meta' in ro.values && ro.values.meta.ref.value.originalData) {
const { indexBuffer, vertexCount, triangleCount } = ro.values.meta.ref.value.originalData;
}
```
> Better handling of processed meshes

- src/extensions/geo-export/controls.ts
- src/extensions/geo-export/glb-exporter.ts
- src/extensions/geo-export/obj-exporter.ts
- src/extensions/geo-export/stl-exporter.ts
- src/mol-canvas3d/canvas3d.ts
When importing some models such as 7NCK to Blender using the geometry exporter, the models are very off the center and make it look like nothing is imported. This PR centers exported models.
This will also be useful when we implement the USDZ format for AR. Apple says that "Base of object should sit on the ground plane (y = 0)" (slide 30 in https://devstreaming-cdn.apple.com/videos/wwdc/2018/603augiuv41xoowslk8/603/603_integrating_apps_and_content_with_ar_quick_look.pdf). iOS AR doesn't automatically center the object. I'm not sure about Android.
Note: I don't factor out the translation matrix calculation because it will be a bit different for USDZ.
> Geometry export: center exported models

- src/mol-geo/geometry/mesh/builder/cylinder.ts
If `Cylinder.setCylinderMat` is called for the first time with `matchDir` set to false, `tmpUp` will be a zero vector and the cylinder will have wrong orientation as shown below.
I discovered this bug while trying to update [molrender](https://github.com/molstar/molrender). It is a bit hard to reproduce this bug in the viewer without modifying the source code, because the axes are shown by default and the cylinders in the axes are created with `matchDir` set to true.
Another way to fix this is to simply change `var tmpUp = Vec3();` to `var tmpUp = Vec3.create(0, 1, 0);` But I think this fix is better because it eliminates side effects from `setCylinderMat`.
> Fix cylinder orientation

- CHANGELOG.md
- src/mol-model-props/computed/helix-orientation.ts
- src/mol-model-props/computed/helix-orientation/helix-orientation.ts
- src/mol-repr/structure/representation/cartoon.ts
- src/mol-repr/structure/visual/polymer-trace-mesh.ts
- src/mol-repr/structure/visual/polymer-tube-mesh.ts
- src/mol-repr/structure/visual/util/polymer/trace-iterator.ts
Fixes #206.
At some point it might be worthwhile to precalculate the trace points...
There are some more things that could be done with the helix-orient data like in NGL but not sure if worthwhile
- http://nglviewer.org/ngl/?script=representation/helixorient (quite narrow use-case...)
- http://nglviewer.org/ngl/?script=representation/rocket (also allows splitting highly bend helices in more components)
--
Colored by hydrophobicity
> Add tubularHelices parameter to Cartoon representation

- src/mol-geo/geometry/mesh/builder/cylinder.ts
This PR uses fewer mathematical operations in `setCylinderMat()`.
> Optimize setCylinderMat()

- src/mol-gl/compute/histogram-pyramid/reduction.ts
Texture framebuffers use in histogram pyramid calculation are cached in a global variable that exists throughout the entire lifetime of the application. These cached objects may become invalid under some circumstances. One example could be a JS application that creates and destroys a Molstar plugin on demand. Framebuffer objects created by the plugin will not be valid when the plugin's instance gets destroyed and recreated at a later time. Density maps will then fail to display as a result and the only way out is to reload the entire page in the browser.
This could possibly be improved by flushing the cache only when it's actually necessary but I couldn't find a place in the code where doing so wouldn't feel really hacky.
> Do not cache LevelTexturesFramebuffers as they may become invalid

- src/extensions/anvil/algorithm.ts
I've had a look at the dubious ANVIL prediction for 3pqr that Alex reported. Seems like lowering the number of sphere points to 140 was a bit too greedy.
175, half of the original value, results in a better prediction in this case while not affecting performance greatly. Calculations for extreme cases like 7cgo or 6nk5 still finish similarly fast.
Left: 140 points, right: 175
> ANVIL: improve prediction for 3pqr

- src/extensions/anvil/algorithm.ts
- the ANVIL prediction depends on the set of amino acids that are considered 'membrane-favoring', this PR adds an alternative classification from TMDET, the TMDET definition shows better performance for porins & most beta-barrel structures and might be useful to some users as a fallback for flawed predictions
- adds a reference to TMDET which, in general, shows striking similarities to ANVIL, it's only fair to give them some credit as well
- fixes prediction for [6y1z](https://www.rcsb.org/3d-view/6Y1Z/1?preset=membrane) which contains amino acids that are not part of an entity
Thanks for having a look!
> ANVIL: add TMDET amino acid classification and reference

- CHANGELOG.md
- src/apps/viewer/index.html
- src/apps/viewer/index.ts
- src/mol-canvas3d/camera.ts
- src/mol-canvas3d/camera/util.ts
- src/mol-canvas3d/canvas3d.ts
- src/mol-canvas3d/helper/interaction-events.ts
- src/mol-canvas3d/passes/draw.ts
- src/mol-canvas3d/passes/pick.ts
- src/mol-geo/geometry/lines/lines.ts
- src/mol-geo/geometry/points/points.ts
- src/mol-gl/renderer.ts
- src/mol-gl/shader/lines.vert.ts
- src/mol-gl/shader/points.vert.ts
- src/mol-math/linear-algebra/3d/vec3.ts
- src/mol-math/misc.ts
- src/mol-model/loci.ts
- src/mol-model/structure/structure/unit/bonds.ts
- src/mol-plugin-state/manager/interactivity.ts
- src/mol-plugin/behavior/dynamic/representation.ts
- src/mol-plugin/config.ts
- src/mol-plugin/context.ts
- src/mol-repr/structure/representation/line.ts
- Fix pickScale not taken into account in line/point shader
- Add pixel-scale & pick-scale GET params to Viewer app
- Fix selecting bonds not adding their atoms in selection manager
- Add ``preferAtoms`` option to SelectLoci/HighlightLoci behaviors
- Make the implicit atoms of bond visuals pickable
- Add ``preferAtomPixelPadding`` to Canvas3dInteractionHelper
- Add points visual to Line representation
Also looks around the initial picked pixel in a spiral of radius 5 until a hit is found.
https://user-images.githubusercontent.com/272250/134830371-c1106aec-3de1-42ae-b096-69b318f5c4d9.mp4
--
An alternative would be to push responsibility to representation objects by passing the pick position to the Representation.getLoci method.
> Picking improvements

- src/mol-plugin-state/manager/structure/measurement.ts
- src/mol-plugin-ui/structure/measurements.tsx
As a followup to #274 I propose the following tweaks to behavior of the measurements feature:
* Show the order in which the selected locis will by used for measurements directly in the 3D structure view. The order is displayed only then the Measurements control is in the 'add' action mode.
* Use the entire element to highlight a loci from additionsHistory. Currently, only the first button with highlights the loci. When a user tries to move or delete an entry from history, they cannot see which loci they are working with in the view.
> Improve measurements user experience

- src/mol-geo/geometry/text/text.ts
- src/mol-plugin-state/manager/structure/measurement.ts
Naturally, I discovered a few minor issues with the newly added measurement labels code. Sorry... :)
* Border width of 0.5 is too wide and may cause visual artifacts. It is reduced to 0.3.
* Default offsetZ value of 2 is most likely okay for ordinary labels but it seems too high for the order labels. If the user zooms in very closely, order labels get clipped off even though the structure itself is still clearly visible. Value of 0.75 seems to improve this a lot without causing the labels to sink into the structure.
* There was a minor glitch in the text rendering code where the border width was initially set at half of the intended value. With the fix in place it might make sense to check if the default border width (0.2?) is not too thick now.
> Tweak measurement order labels

- src/mol-io/reader/_spec/sdf.spec.ts
- src/mol-io/reader/sdf/parser-v3-util.ts
- src/mol-io/reader/sdf/parser.ts
Added a set of utility functions for parsing atoms and bonds from v3000 sd files.
Updated the existing sdf parser to determine the version and run the v3000 sd file parser functions instead of the default v2000 ones.
Added tests to verify parsing functionality for example v3000 ctab
resolves #286
> Added the ability to handle v3000 sd files

- src/extensions/geo-export/obj-exporter.ts
- src/extensions/geo-export/usdz-exporter.ts
The current code throws an error when exporting the default 1TQN as USDZ or OBJ. ("Cannot read properties of undefined (reading 'vertexCount')".) This is because it tries to read the `vertexCount` property of `input.mesh`, which is only defined for GraphicsRenderObjects that share the same vertex and normal arrays for every instance, such as Mesh or TextureMesh. For other kinds of GraphicsRenderObjects, `input.meshes` is defined. The proper way to read `vertexCount` of an instance is to use `MeshExporter.getInstance(input, instanceIndex).vertexCount`, which takes care of `input.mesh` and `input.meshes`.
> Fix USDZ and OBJ export

- scripts/clean.js
The original cleanup script required at least Node v14.14 . The updated version should work with any version of Node that can be expected to build Molstar.
> Make cleanup script work with older vesions of Node.js

- src/extensions/mp4-export/controls.ts
Under Export Animation, when exporting State Snapshots, the canApply values won't get updated when additional state snapshots are added (or removed). Will keep reporting 'At least 2 states required.' and requires e.g. switching temporarily to another animation type.
> update State Snapshots canApply when snapshots are added

- CHANGELOG.md
- src/apps/docking-viewer/index.html
- src/apps/docking-viewer/index.ts
- src/apps/viewer/embedded.html
- src/apps/viewer/index.html
- src/apps/viewer/index.ts
- src/examples/alpha-orbitals/index.ts
- src/examples/basic-wrapper/index.html
- src/examples/basic-wrapper/index.ts
- src/examples/lighting/index.html
- src/examples/lighting/index.ts
- src/examples/proteopedia-wrapper/index.html
- src/examples/proteopedia-wrapper/index.ts
- src/mol-plugin-ui/index.ts
- There have been two ways to create a plugin instance and both were a little bit broken. 
- Taking the opportunity of 3.0 to improve on the situation by introducing ``createPluginUI`` and removing the previous options.
> mol-plugin-ui/createPluginUI

- src/mol-gl/compute/marching-cubes/isosurface.ts
- src/mol-gl/shader/marching-cubes/isosurface.frag.ts
- src/mol-repr/structure/visual/gaussian-surface-mesh.ts
- src/mol-repr/volume/isosurface.ts
- src/tests/browser/marching-cubes.ts
Isosurface group id from GPU MC was wrong for axis order other than 012. Fixes #331.
Generally it would probably be better to handle axis order from the start when doing gpu mc which would also simplify data upload to the gpu a bit. Another time.
> fix gpu isosurface group id

- CHANGELOG.md
- src/mol-plugin-state/transforms/representation.ts
- src/mol-repr/structure/representation/gaussian-surface.ts
- src/mol-repr/structure/representation/gaussian-volume.ts
- src/mol-repr/structure/representation/label.ts
- src/mol-repr/structure/representation/molecular-surface.ts
- src/mol-repr/structure/visual/gaussian-density-volume.ts
- src/mol-repr/structure/visual/gaussian-surface-mesh.ts
- src/mol-repr/structure/visual/gaussian-surface-wireframe.ts
- src/mol-repr/structure/visual/label-text.ts
- src/mol-repr/structure/visual/molecular-surface-mesh.ts
- src/mol-repr/structure/visual/molecular-surface-wireframe.ts
- src/mol-repr/structure/visual/util/common.ts
- src/mol-repr/structure/visual/util/gaussian.ts
- src/mol-repr/structure/visual/util/molecular-surface.ts
Allows, for example, to create a Gaussian surface based on B-factors.
> Use size theme in molecular/gaussian surface & label representations

- src/mol-plugin-ui/structure/volume.tsx
Folks on our end are interested in a more user-friendly error message when volume streaming can't be enabled. We would like a distinction between unexpected/parsing errors and the case where a structure just doesn't provide density data, indicated by a 404.
This would bring the error messages in alignment with the assembly symmetry component.
> Volume Streaming Error Message

- src/mol-model/structure/export/categories/secondary-structure.ts
This ensures that SSE information is exported for transformed structures.
`const u = unit.units[0];` is used in other places, I assume this is also the way to go here.
> iterate over `structure.unitSymmetryGroups`, fixes #364

- CHANGELOG.md
- src/mol-plugin-state/builder/structure/representation-preset.ts
- src/mol-plugin-state/builder/structure/representation.ts
- src/mol-plugin-ui/controls.tsx
- src/mol-plugin-ui/controls/icons.tsx
- src/mol-plugin-ui/structure/quick-styles.tsx
I propose this as a solution to #363 so we can have reusable representation presets and one-click styles.
Reset: Applies default representation preset. Set outline and occlusion effects to defaults.
Illustrative: Applies illustrative representation preset. Enables outline and occlusion effects. Enables ignore-light parameter.
Stylized: Applies no representation preset. Enables outline and occlusion effects. Enables ignore-light representation parameter.
> Quick styles

- CHANGELOG.md
- src/mol-plugin/behavior/dynamic/selection/structure-focus-representation.ts
- src/mol-repr/structure/representation/cartoon.ts
I am proposing some tweaks to the cartoon and focus representation defaults
- Cartoon: use ``nucleotide-ring`` instead of ``nucleotide-block``
- Focus: use ``xrayShaded`` instead of opacity; adjust target size; don't show non-covalent interactions twice
New
Old
> cleaner default representation style

- CHANGELOG.md
- src/mol-model/structure/structure/util/superposition-sifts-mapping.ts
- src/mol-plugin-ui/structure/superposition.tsx
This addresses #371.
Is it intentional that the camera only resets for the UniProt alignment but not for the ones based on chains/atoms?
> Add TraceOnly option for Structure Superposition

- src/mol-plugin/behavior/dynamic/volume-streaming/util.ts
There was a breaking change wrt the format of EMDB XML header files (https://www.wwpdb.org/news/news?year=2021#610ad31fef055f03d1f222bb). This causes all loading of EM maps on rcsb.org & molstar.org to fail.
> parse contour-level from emdb v3 header files

- tsconfig.commonjs.json
- tsconfig.json
As a follow-up to https://github.com/molstar/molstar/issues/296 I noticed that the NPM package JS files all have a comment like `//# sourceMappingURL=context.js.map` at the bottom of the file that references a now non-existent source map file. This also caused a flood of Webpack errors when trying out locally. I was able to get rid of the comments in the output JS by disabling one of the TypeScript configs
> Disable ts config that leads to sourceMappingURL comment

- CHANGELOG.md
- src/apps/docking-viewer/viewport.tsx
- src/examples/lighting/index.ts
- src/mol-canvas3d/passes/draw.ts
- src/mol-canvas3d/passes/multi-sample.ts
- src/mol-canvas3d/passes/postprocessing.ts
- src/mol-gl/scene.ts
- src/mol-gl/shader/postprocessing.frag.ts
- src/mol-plugin-ui/structure/quick-styles.tsx
- src/mol-plugin/util/viewport-screenshot.ts
- Reuse occlusion for secondary passes during multi-sampling
- Check if marking passes are needed before doing them
- Add ``scaleFactor`` parameter to adjust resolution of occlusion calculation
Not 100% sure about the default ``scaleFacor`` as there are some "halo" artifacts but the performance gain is substantial, ~1.8x for 1TQN with molecular surface. => Set default to 1, i.e. no down sampling. Doesn't look good enough in general, imho, if the scene has fine details. Leave it in as an option, though, still useful in many cases.
> Improve AO performance

- src/extensions/dnatco/confal-pyramids/property.ts
- src/extensions/dnatco/confal-pyramids/util.ts
This fixes some Confal pyramids failing to display in some peculiar structures such as [https://blackbox.ibt.biocev.org/devel_molstar/RCSB/cif_dnatco_updated/1jbs_v32C35A23.cif.gz](https://blackbox.ibt.biocev.org/devel_molstar/RCSB/cif_dnatco_updated/1jbs_v32C35A23.cif.gz).
(FYI, I have some more changes to the DNATCO extension lined up but this time I'll try to break them down to smaller MRs so things don't stall like last time)
> DNATCO extension: Fix off-by-one error in element lookup

- CHANGELOG.md
- src/mol-model/structure/query/queries/generators.ts
The Disulfide Bridges selection includes wrong residues.
> Fix unit mapping in bondedAtomicPairs MolScript query

- CHANGELOG.md
- src/mol-plugin/behavior/dynamic/volume-streaming/util.ts
Fixes an issue introduced by me in https://github.com/molstar/molstar/pull/377: It's imperative to select the `map` tag before looking for the contour list.
Happens e.g. for 6Z0S.
> fix volume streaming for entries with multiple contour lists

- src/mol-plugin-ui/plugin.tsx
- src/mol-plugin-ui/spec.ts
Added an option to the components spec to allow disabling of the drag-and-drop overlay for Molstar that loads files into the viewer. By default the drag overlay is enabled, just as it was before.
> Added an option to disable the drag overlay

- CHANGELOG.md
- src/mol-gl/webgl/program.ts
- src/mol-gl/webgl/uniform.ts
Headless-gl requires a `[0]` suffix when getting the location of array uniforms (https://github.com/stackgl/headless-gl/issues/170). Without neither `uLightDirection` nor `uLightColor` get set.
See https://github.com/molstar/molrender/issues/3#issuecomment-1117615459.
> proposed fix for headless-gl issues

- CHANGELOG.md
- src/mol-geo/geometry/color-data.ts
- currently, instances of the same chain get colored identically
- looks like a typo
> Fix Polymer Chain Instance Coloring

- src/mol-plugin-ui/viewport/screenshot.tsx
This should solve the error:
Warning: Can't perform a React state update on an unmounted component.
This is a no-op, but it indicates a memory leak in your application.
To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
> DownloadScreenshotControls: componentWillUnmount

- src/cli/chem-comp-dict/create-ions.ts
- src/cli/chem-comp-dict/create-saccharides.ts
- src/cli/chem-comp-dict/create-table.ts
- src/cli/chem-comp-dict/util.ts
- add CLI arguments that allow downloading the CCD from non-standard URLs
- useful to process CCD data that isn't released yet and for custom CCDs
- technically a breaking change to the signature of `ensureDataAvailable()` -- let me know if this should be done in a less invasive fashion
> Download CCD from Configurable URL

- CHANGELOG.md
- src/extensions/dnatco/confal-pyramids/property.ts
- src/extensions/dnatco/confal-pyramids/representation.ts
- src/extensions/dnatco/confal-pyramids/types.ts
- src/extensions/dnatco/confal-pyramids/util.ts
Current code uses a rather clumsy way to match NtC steps with the corresponding residues in the structure. It currently takes the two residues that make up a step, looks up a bunch of information about it and then constructs a "step name" string. The step name is a key in a map that maps step names to indices in the array of all available steps. This is rather slow and involves some crufty code.
Instead of using the step name as the identifier, this patch splits the mapping up per model -> chain -> residue. Since a step is made up of two consecutive residues, the seq_id of the first residue in a step can be used as the key in the map that contains the final mapping of residues to elements the array of steps.
If there are alternate positions, there may be multiple steps with the same …
> Change the lookup logic of NtC steps from residues

- CHANGELOG.md
- src/mol-plugin-state/actions/file.ts
As far as I can tell, Molstar Viewer will automatically decompress assets only when come from a local file. There is support for remote Zip archives but getting Gzipped files from a remote source does not seem possible. This little patch adds the option to download Gzipped files.
Is there a reason why there is no direct support for download of compressed structure files etc? I might be missing something obvious...
> Allow download of Gzipped files

- CHANGELOG.md
- src/mol-model/structure/structure/util/superposition-sifts-mapping.ts
Example usage:
```ts
alignAndSuperposeWithSIFTSMapping(structures, {
includeResidueTest: loc => StructureProperties.atom.B_iso_or_equiv(loc) < 90
})
```
More complicated usage (check all atoms in the residue):
```ts
alignAndSuperposeWithSIFTSMapping(structures, {
includeResidueTest: (loc, _, start, end) => {
for (let eI = start; eI < end; eI++) {
loc.element = eI;
if (StructureProperties.atom.B_iso_or_equiv(loc) > 90) return false;
}
return true;
}
})
```
> alignAndSuperposeWithSIFTSMapping includeResidueTest option

- CHANGELOG.md
- src/apps/docking-viewer/index.ts
- src/apps/docking-viewer/viewport.tsx
- src/mol-model-props/computed/representations/interactions-inter-unit-cylinder.ts
- src/mol-model-props/computed/representations/interactions-intra-unit-cylinder.ts
- src/mol-model-props/computed/representations/shared.ts
Only has an effect when "includeParent" is enabled. "Stub" shows just the child side of interactions to the parent. "Full" shows both sides of interactions to the parent. "Between" shows only interactions to the parent.
The way to use it is to create a structure selection that only has the ligand you want to see interactions to and then set the parentDisplay to "between".
> add parentDisplay param to interactions repr

- CHANGELOG.md
- src/apps/viewer/app.ts
- src/apps/viewer/index.html
- src/extensions/geo-export/ui.tsx
- src/extensions/mp4-export/controls.ts
- src/mol-canvas3d/canvas3d.ts
- src/mol-plugin-ui/controls/screenshot.tsx
- src/mol-plugin-ui/left-panel.tsx
- src/mol-plugin-ui/viewport/canvas.tsx
- src/mol-plugin-ui/viewport/screenshot.tsx
- src/mol-plugin-ui/viewport/simple-settings.tsx
- src/mol-plugin/config.ts
- src/mol-plugin/context.ts
Support for ``failIfMajorPerformanceCaveat`` webgl attribute. Add ``PluginConfig.General.AllowMajorPerformanceCaveat`` and ``allow-major-performance-caveat`` Viewer GET param.
With this PR, the plugin (and Viewer) will fail with a webgl not available error if no hardware acceleration is available, i.e., GPU emulated with software renderer, which makes molstar unusable slow in almost all cases.
Chrome has a setting "Use hardware acceleration when available" which can be used to test this.
When using molstar to render images server-side a GPU is often not available and a software renderer is OK, which is still support with the new options.
> add support for failIfMajorPerformanceCaveat

- src/mol-canvas3d/passes/passes.ts
Fixes an issue where hiding the canvas element would trigger an error. Used 2x2 as the minimum dimensions as discussed in the issue: https://github.com/molstar/molstar/issues/560
> Fix "empty textures" error on empty canvas

- CHANGELOG.md
- src/mol-io/common/binary-cif/array-encoder.ts
Optimizes `packingSize` function to be ~2-8x faster depending on the weather.
Wrote this script to compare the optimization to the old implementation:
```js
function packingSizeUnsinged(value, upperLimit) {
return ((value / upperLimit) | 0) + 1;
}
function packingSizeSigned(value, upperLimit) {
return value >= 0
? ((value / upperLimit) | 0) + 1
: ((-value / (upperLimit + 1)) | 0) + 1;
}
function packingSizeOld(value, upperLimit) {
const lowerLimit = -upperLimit - 1;
let size = 0;
if (value === 0) {
size += 1;
} else if (value > 0) {
size += Math.ceil(value / upperLimit);
if (value % upperLimit === 0) size += 1;
} else {
size += Math.ceil(value / lowerLimit);
if (value % lowerLimit === 0) size += 1;
}
return size;
}
let upperLimit = 0xFFFF;
for (let i = 0; i < 10000; i++) {
if …
```
> Optimize BinaryCIF integer packing

- CHANGELOG.md
- src/mol-model-props/common/custom-model-property.ts
- src/mol-model/structure/model/model.ts
- src/mol-plugin-state/builder/structure/hierarchy-preset.ts
- src/mol-plugin/behavior/dynamic/custom-props/structure-info.ts
- src/mol-theme/color.ts
- src/mol-theme/color/element-symbol.ts
- src/mol-theme/color/illustrative.ts
- src/mol-theme/color/model-index.ts
- src/mol-theme/color/trajectory-index.ts
- src/mol-util/color/color.ts
- src/mol-util/color/distinct.ts
Based off discussion for [molstar-577](https://github.com/molstar/molstar/issues/577)
* Renamed the existing model-index color theme to trajectory-index
* Created a new model-index color theme that uses `Model.Index` to determine color
* Added the new model-index color theme as an option in the element-symbol color theme for carbon color
* Added the option to alter the element-symbol's carbon color by the saturation/lightness parameters
* If we feel this change is not needed then I can remove it
Contains a 'breaking' change in that the model-index theme no longer works at all like it used to.
> Model index updates & carbon color

- src/mol-gl/shader/chunks/apply-light-color.glsl.ts
@arose here is the PR addressing #558. I had to clamp from 0.01 to 0.99 cause I just noticed that when exporting images larger than the viewport the issue was still visible
> Transparent bg fix

- CHANGELOG.md
- src/mol-util/assets.ts
Tiny quality-of-life improvement that extends the handling of zip/gzip assets to URLs.
https://files.rcsb.org/download/4HHB.cif.gz
https://files.rcsb.org/download/4HHB.pdb.gz
https://models.rcsb.org/4HHB.bcif.gz
> keep asset url to detect compression

- CHANGELOG.md
- src/mol-util/assets.ts
My apologies for the hassle. Validation reports are working again.
> Fix Handling of Gzipped Assets by Reverting #615

- CHANGELOG.md
- src/mol-model/structure/structure/unit/bonds/inter-compute.ts
PDB `1e1y` wasn't showing bond even though it was present in `struct_conn` => Decide a unit pair is valid if it has a valid struct conn record.
> Fix struct_conn bond assignment for ions

- src/extensions/dnatco/behavior.ts
- src/extensions/dnatco/confal-pyramids/representation.ts
- src/extensions/dnatco/confal-pyramids/util.ts
- src/extensions/dnatco/ntc-tube/util.ts
I just realized that when there are discontinuities in chains the mesh building logic won't detect them and draw things wrong. See the example below:
Wrong:
Fixed:
This can probably only happen if the user applies a selection on the structure. I used the following input to create the testing example:
- Structure: https://dnatco.datmos.org/v4.1/RCSB/cif_dnatco_updated/1bna_v41C35A23.cif.gz
- Selection script:
```
(sel.atom.res
(or
(in-range atom.resno 1 2)
(or
(in-range atom.resno 5 9)
(or
(in-range atom.resno 11 12)
(or
(in-range atom.resno 13 14)
(in-range atom.resno 16 21)
)
)
)
)
)
```
I'm sorry for not catching this sooner.
> Fix NtC tube and Confal pyramids mesh when there are discontinuous chains

- CHANGELOG.md
- src/servers/volume/pack/main.ts
The shell exit code was 0 when an error happened. Like this it will behave like any CLI program should
> Fixing exit code for volume packer

- CHANGELOG.md
- src/mol-math/linear-algebra/matrix/principal-axes.ts
I fixed the small bug in PCA, mentioned here #722 .
When the number of points is 1, PCA axes should be an identity matrix.
> Fixed degenerate case (1-point) in PCA

- CHANGELOG.md
- package.json
- src/mol-util/nodejs-shims.ts
On updating molstar I noticed some runtime errors were being thrown because we have `document` polyfilled in a NodeJS env. This change updates the conditionals in nodejs-shims.ts to avoid checking `typeof document === 'undefined'`.
> Change nodejs-shim conditional to avoid checking `document` object existence

- CHANGELOG.md
- src/mol-util/input/input-observer.ts
Use ResizeObserver to trigger `handleResize` when the canvas's parent element changes size. This handles changes that affect the viewer dimensions even if the window itself does not emit a resize event.
closes #749
> Handle resizing viewer element when window remains the same size

- CHANGELOG.md
- src/mol-gl/renderer.ts
Avoid rendering of fully transparent renderables (on renderMarkingDepth)
> Marking depth avoid alpha 0 rendering

- CHANGELOG.md
- src/mol-math/linear-algebra/3d/mat3.ts
- src/mol-plugin-state/manager/camera.ts
- src/mol-plugin-state/manager/focus-camera/orient-axes.ts
- src/mol-plugin-ui/left-panel.tsx
- src/mol-plugin-ui/skin/base/components/viewport.scss
- src/mol-plugin-ui/viewport.tsx
- src/mol-plugin-ui/viewport/simple-settings.tsx
- src/mol-plugin/behavior/static/camera.ts
- src/mol-plugin/commands.ts
I added "Zoom All", "Orient Axes", "Reset Axes" buttons. These will show when one hovers over the "Reset Camera" button. "Zoom All" does the same as "Reset Camera" (we might drop it).
"Orient Axes"/"Reset Axes" rotate camera to align with PCA/XYZ coordinates. I exposed the same functionality via `PluginCommands` and `plugin.manager.camera` as well.
> Added "Zoom All", "Orient Axes", "Reset Axes" buttons

- CHANGELOG.md
- src/mol-gl/_spec/renderer.spec.ts
- src/mol-gl/webgl/render-item.ts
- src/mol-gl/webgl/resources.ts
- src/mol-gl/webgl/vertex-array.ts
Reuse of vertex arrays among GL programs seems to break rendering. With commit 291d7abb7804d58e2ed4a35601715d50e6d4b8b8 applied, cartoon visuals look like this
and it's not easy to face up when the whole structure is black. Suggested partial revert fixes the problem for me.
This issue appears to be specific to only some OpenGL driver because amongst the computers I have at hand ATM I can only reproduce it on a laptop with AMD Vega 8 and Mesa 23.
> Fix broken rendering caused by changes in 291d7abb7804d58e2ed4a35601715d50e6d4b8b8

- CHANGELOG.md
- src/extensions/dnatco/ntc-tube/util.ts
I recently ran into a structure that is missing C5' atoms in a few places. C5' atoms are control points of the NtC tube spline and without them it's not possible to render the segment. The most reasonable thing to do seems to be to just skip any segments for which we cannot construct the NtC tube spline.
4v4t example:
Broken:
The long spokes are the result of the point coordinates defaulting to [0,0,0] when the requested atom cannot be found.
Ok:
> Fix rendering of NtC tube when some of the required atoms are missing

- CHANGELOG.md
- src/mol-model/structure/structure/element/location.ts
- src/mol-model/structure/structure/element/loci.ts
- src/mol-repr/representation.ts
- src/mol-repr/shape/representation.ts
- src/mol-repr/structure/complex-representation.ts
- src/mol-repr/structure/complex-visual.ts
- src/mol-repr/structure/units-representation.ts
- src/mol-repr/structure/units-visual.ts
- src/mol-repr/util.ts
- src/mol-repr/visual.ts
- src/mol-repr/volume/representation.ts
Add `.eachLocation` to representation/visual interface for when `.getAllLoci` is too coarse.
> add eachLocation to representation/visual interface

- CHANGELOG.md
- src/extensions/dnatco/ntc-tube/color.ts
With some practical experience we found out that having the NtC tube painted accordingly to NtCs could make the structure look "busy" and difficult to read in some situations. This patch adds an alternative color theme where everything but the residue and step boundaries are painted in uniform color.
vs.
> Add a uniform color theme for NtC tube that still paints the residue and segment dividers in a different color

- CHANGELOG.md
- src/mol-model/structure/structure/structure.ts
- src/mol-model/structure/structure/unit/bonds/inter-compute.ts
- Previously fixed this issue for ions, but it is present for waters as well. 
- Added new method which checks that a pair of units has a `struct_conn` record and if it does, it overrides all the other settings.
- A test case is `1tqn`
> fix struct_conn for waters

- src/extensions/sb-ncbr/partial-charges/labels.ts
- src/extensions/sb-ncbr/partial-charges/property.ts
@MergunFrimen your PR actually broke labels for structures without the required categories. One thing to be aware of for the next time. Also optimized `getParams` function by caching the `getData` explicitly.
> SB NCBR Partial Charges: fix labels & optimize getData

- CHANGELOG.md
- docs/interesting-pdb-entries.md
- src/mol-model/structure/model/types.ts
Added hydroxyproline (HYP, a common component of the collagen) to the list of amino acids
> Add HYP to the list of amino acids

- CHANGELOG.md
- src/mol-repr/structure/units-representation.ts
- src/mol-repr/volume/representation.ts
This brings back the behavior where one can hide volume certain channels and they won't reappear later on, e.g. when focusing on a residue.
Adjusts other properties as well. Let me know if this has any implications.
> Adjust VolumeRepresentation#setState

- CHANGELOG.md
- src/mol-geo/geometry/base.ts
- src/mol-repr/structure/visual/polymer-trace-mesh.ts
- src/mol-repr/structure/visual/polymer-tube-mesh.ts
- src/mol-repr/structure/visual/util/polymer.ts
- src/mol-theme/color.ts
- src/mol-theme/color/cartoon.ts
- src/mol-theme/color/element-symbol.ts
- src/mol-theme/color/illustrative.ts
- src/mol-theme/color/uniform.ts
Support more flexible coloring of cartoon visuals.
- Add `nucleicProfile` parameter to cartoon representation
- Add `cartoon` theme with separate colorings for for mainchain and sidechain visuals
> Cartoon improvements

- CHANGELOG.md
- src/mol-geo/geometry/cylinders/cylinders.ts
- src/mol-geo/geometry/direct-volume/direct-volume.ts
- src/mol-geo/geometry/mesh/mesh.ts
- src/mol-geo/geometry/spheres/spheres.ts
- src/mol-geo/geometry/texture-mesh/texture-mesh.ts
- src/mol-gl/renderable/cylinders.ts
- src/mol-gl/renderable/direct-volume.ts
- src/mol-gl/renderable/mesh.ts
- src/mol-gl/renderable/spheres.ts
- src/mol-gl/renderable/texture-mesh.ts
- src/mol-gl/renderer.ts
- src/mol-gl/shader/chunks/apply-light-color.glsl.ts
- src/mol-gl/shader/chunks/common.glsl.ts
- src/mol-repr/util.ts
Good for making spacefill representation transparent to reveal a ligand.
> add inverted xray-shaded option

- CHANGELOG.md
- src/mol-geo/geometry/spheres/spheres.ts
- src/mol-gl/renderable/spheres.ts
- src/mol-gl/shader/chunks/common-clip.glsl.ts
- src/mol-gl/shader/spheres.frag.ts
- src/mol-gl/shader/spheres.vert.ts
To get more performance when rendering many spheres at the expense of artefacts. Best used when geometry does not overlap or when there is no lighting and uniform coloring.
> add approximate option for spheres rendering

- CHANGELOG.md
- src/mol-theme/color/element-symbol.ts
I added 'Chain Instance' and 'Uniform' options for 'Carbon Color' param (in Color Theme: Element Symbol)
> Add 'Chain Instance' and 'Uniform' options for 'Carbon Color' param

- CHANGELOG.md
- src/mol-plugin-state/transforms/model.ts
Proposal to fix #877 by ensuring that the CCD route only triggers if `chem_comp_atom` is defined and, simultaneously, no conventional coordinates are present.
> Fix logic for trajectoryFromCCD

- CHANGELOG.md
- src/mol-model-formats/structure/util.ts
In our scenario that simulate battery material include some elements like `Li`, `B`, `F` etc. But I noticed that molstar can not render those elements correctly.
[incorrect example here](https://github.com/molstar/molstar/issues/882)
So I added some elements that our scenario requires into the function `guessElementSymbolString`. But I'm not sure if there are any other elements that need to be added.
If there are any other elements that need to be added, please let me know, or perhaps the project's author could add them.
Thank you~
> add some elements name for `guessElementSymbolString` function

- CHANGELOG.md
- src/mol-repr/structure/visual/label-text.ts
Allows toggling of hydrogen atoms for label representations.
Follow-up to https://github.com/molstar/molstar/pull/731#issuecomment-1558604204.
> Allow toggling of hydrogens as part of `LabelTextVisual`

- CHANGELOG.md
- src/extensions/wwpdb/ccd/representation.ts
Gives control over aromatic bonds: depict delocalized ring or actual bonds as annotated by the CCD.
> CCD extension: Make visuals for aromatic bonds configurable

- CHANGELOG.md
- src/mol-io/writer/mol/encoder.ts
- src/mol-io/writer/mol2/encoder.ts
- src/servers/model/CHANGELOG.md
- src/servers/model/version.ts
Atom count reported as part of SDF/MOL/MOL2 export may not match the actual file content. Exported file won't open in RDKit/OpenBabel/etc.
Happens e.g. for 6t6x: https://models.rcsb.org/v1/6t6x/ligand?auth_seq_id=301&label_asym_id=B&encoding=cif. This instance of MQW contains `H462`, an atom that isn't described by the CCD and can't get exported.
> ModelServer ligand queries: fix atom count reported by SDF/MOL/MOL2 export

- CHANGELOG.md
- src/mol-plugin-state/transforms/model.ts
I added an optional parameter `blockIndex` to TrajectoryFromMmCif transformer. Defaults to 0 and only applies when `blockHeader` is undefined or empty string.
> Add `blockIndex` parameter to TrajectoryFromMmCif

- CHANGELOG.md
- src/extensions/rcsb/validation-report/prop.ts
- src/mol-plugin/config.ts
Validation reports are currently broken because `ftp.rcsb.org` now only works with FTP. This fixes validation reports by pointing to the updated URL.
> Update RCSB PDB validation report URL

- CHANGELOG.md
- src/mol-repr/structure/visual/element-point.ts
- src/mol-repr/structure/visual/util/element.ts
- src/mol-repr/structure/visual/util/link.ts
Previous version could result in the bounding sphere not updating even for a large change in conformation.
> fix bounding sphere calculations for "element-like" visuals

- CHANGELOG.md
- src/mol-plugin-ui/plugin.tsx
- src/mol-plugin-ui/skin/base/base.scss
- src/mol-plugin/context.ts
Based on the response I gave for #927 I thought it would be nice to have built-in support for the "initialized" functionality.
> add PluginContext.initialized promise

- CHANGELOG.md
- src/mol-plugin-ui/viewport/simple-settings.tsx
Probably just copy-and-paste. Causes the panel on the right to disappear forever if interacting with the Settings panel and `components.controls.left = 'none'`.
> Fix layout typo

- CHANGELOG.md
- src/mol-theme/label.ts
I would like to create `condensed` labels for bonds. This allows doing so with the default `lociLabel(loci, options)`.
> Add `options` support for default bond labels

- CHANGELOG.md
- src/mol-geo/geometry/spheres/spheres.ts
- src/mol-gl/renderable/spheres.ts
- src/mol-gl/shader/spheres.frag.ts
- src/mol-gl/shader/spheres.vert.ts
- Add `clipPrimitive` option to spheres geometry, clipping whole spheres instead of cutting them
> add clipPrimitive option to spheres geometry

- CHANGELOG.md
- src/mol-io/writer/ligand-encoder.ts
- src/mol-io/writer/mol/encoder.ts
- src/mol-io/writer/mol2/encoder.ts
- src/servers/model/version.ts
Some entries have additional (hydrogen) atoms that aren't present in the CCD. This may shift atom indices and can butcher bond information.
This PR addresses this by ignoring all atoms that aren't also registered in the CCD.
Example: https://models.rcsb.org/v1/5sak/ligand?auth_seq_id=404&label_asym_id=E&encoding=mol2
> ModelServer SDF/MOL2 ligand export: fix atom indices for atoms not present in the CCD

- CHANGELOG.md
- package.json
- src/mol-plugin-ui/plugin.tsx
On Safari, `dataTransfer` is not populated during the drag operation. Thus, the drag overlay of Mol* was never getting active.
This change checks if we are on a Safari browser by checking the `userAgent`, if so, then forces the `showDragOverlay` variable to true.
> Fixed drag and drop overlay on WebKit and Safari

- CHANGELOG.md
- src/mol-plugin-state/transforms/representation.ts
- src/mol-plugin-ui/controls.tsx
- src/mol-plugin-ui/controls/parameters.tsx
- src/mol-plugin-ui/skin/base/components/controls.scss
- src/mol-plugin-ui/skin/base/components/viewport.scss
- src/mol-plugin/behavior/dynamic/representation.ts
- src/mol-repr/shape/loci/label.ts
- src/mol-util/param-definition.ts
ping @corredD 
- Add `snapshotKey` and `tooltip` params to loci `LabelRepresentation`
- Update `FocusLoci` behavior to support `snapshotKey` param
- Clicking a visual with `snapshotKey` will trigger that snapshot
- Render multiline loci label tooltips as Markdown
- `ParamDefinition.Text` updates:
- Support `multiline` inputs
- Support `placeholder` parameter
- Support `disableInteractiveUpdates` to only trigger updates once the control loses focus
> Interative labels & related changes

- CHANGELOG.md
- package-lock.json
- package.json
resolves #1031 
Based on discussion in issue this PR moves the optional dependencies related to running mol* on Node (i.e. in a headless context) to be optional peer dependencies instead of just optional dependencies.
One dependency that I made an exception for was `jpeg-js` - since the `@types/jpeg-js` package is now [just a stub](https://www.npmjs.com/package/@types/jpeg-js) (i.e. it does not actually provide any types), I made `jpeg-js` a regular dependency because the build will fail without the types provided by the package. I _think_ an alternative would be to make it both a devDependency and an optional peer dependency but given that it is pure JS and relatively small, I was not too concerned about making it a regular dependency.
Confirmed that the build succeeds locally after …
> Move most headless context deps to optional peer dependencies and remove `@types/jpeg-js`

- CHANGELOG.md
- src/mol-io/common/binary-cif/array-encoder.ts
- src/mol-io/writer/cif/encoder/binary.ts
Fixes BinaryCIF encoder edge cases caused by re-encoding an existing BinaryCIF file. See #1040.
The issues:
- The `ArrayEncoder.fromEncoding` added extra `byte-array` encoding due to implementation details (`integer-packing` adds `byte-array` automatically).
- The automatic column encoding classifier could determine a column has a numeric type on per-entry basis (e.g. using the `cif2bcif` tool), but in the schema the column would be marked as `str`. This caused the encoder to apply numeric-only encoding to a string type, resulting a weird behavior (e.g. in `pdbx_chem_comp_identifier.program_version`)
> BinaryCIF encoder fixes

- CHANGELOG.md
- src/mol-math/linear-algebra/3d/minimize-rmsd.ts
Fix a bug where the result was `NaN` if the first array way longer then the 2nd.
> fix RMSD minification bug

- CHANGELOG.md
- src/apps/mesoscale-explorer/data/cellpack/preset.ts
- src/apps/mesoscale-explorer/data/generic/preset.ts
- src/apps/mesoscale-explorer/data/mmcif/preset.ts
- src/apps/mesoscale-explorer/data/petworld/preset.ts
- src/apps/mesoscale-explorer/data/state.ts
- src/apps/mesoscale-explorer/ui/entities.tsx
- src/mol-plugin-state/transforms/data.ts
Enable to switch to illustrative color scheme in the tree. Use previously applied color at entity level so we can change the color. 
Is there an easy way to access more coloring options ?
> enable illustrative color scheme in the tree

- CHANGELOG.md
- src/apps/mesoscale-explorer/behavior/camera.ts
…'. How can we expose all the MesoFocusLociProps in the UI ? So that user can easily toggle the centerOnly and change the transition duration...
In mesoscale explorer the camera left button click was translating the camera to the selection. Instead we want to have the option between this behavior and a zoom and center behavior. I exposed the toggle as a key binding. But would prefer to have all the MesoFocusLociParams exposed in a collapsible <ParamControler> that I could add somewhere in the interface. Another option would be to use a doubleClick to trigger the centerFocus, but I havnt found a binding for it.
> mesoscale explorer centerOnly behavior

- CHANGELOG.md
- src/apps/docking-viewer/viewport.tsx
- src/apps/mesoscale-explorer/ui/states.tsx
- src/examples/lighting/index.ts
- src/mol-canvas3d/passes/multi-sample.ts
- src/mol-canvas3d/passes/postprocessing.ts
- src/mol-gl/shader/ssao-blur.frag.ts
- src/mol-plugin-ui/structure/quick-styles.tsx
- src/mol-plugin/util/headless-screenshot.ts
- src/mol-plugin/util/viewport-screenshot.ts
Reported in #1122.
Add `reuseOcclusion` parameter to multi-sample pass. This helps with the first artifact reported. It happens because we reuse the occlusion data in the multi-sample pass for performance. We try to correct for the jitter but apparently it dos not (fully) work. As an alternative/workaround we can disable by default in screenshots.
Add `blurBias` parameter to occlusion pass. Not sure if there is an automatic way to calculate a "correct" value but 0.5 seems to work well. There was a previous issue related to that value in the synaptic gap model, @giagitom, can you check?
> fixes for SSAO edge artifacts

- CHANGELOG.md
- src/extensions/model-archive/quality-assessment/color/plddt.ts
Support reading score from B-factor in pLDDT color theme to simplify coloring models.
#736, #849, #1060, 
FYI: @mzhang5579, @mdanner93, @mouhandalkadri
> support reading score from B-factor in pLDDT color theme

- CHANGELOG.md
- src/mol-geo/geometry/cylinders/cylinders.ts
- src/mol-geo/geometry/direct-volume/direct-volume.ts
- src/mol-geo/geometry/mesh/mesh.ts
- src/mol-geo/geometry/spheres/spheres.ts
- src/mol-geo/geometry/texture-mesh/texture-mesh.ts
- src/mol-gl/renderable/cylinders.ts
- src/mol-gl/renderable/direct-volume.ts
- src/mol-gl/renderable/mesh.ts
- src/mol-gl/renderable/schema.ts
- src/mol-gl/renderable/spheres.ts
- src/mol-gl/renderable/texture-mesh.ts
- src/mol-gl/renderer.ts
- src/mol-gl/shader-code.ts
- src/mol-gl/shader/chunks/apply-light-color.glsl.ts
- src/mol-gl/shader/chunks/common-frag-params.glsl.ts
- src/mol-gl/shader/chunks/common.glsl.ts
- src/mol-gl/shader/direct-volume.frag.ts
This PR adds quantized lighting at representation level. Here are some examples
> Add quantized lighting option

- CHANGELOG.md
- src/mol-plugin/context.ts
Allow sharing single canvas3d context with multiple plugins that need to be disposed.
> doNotDisposeCanvas3DContext option in PluginContext.dispose

- CHANGELOG.md
- src/mol-plugin-state/actions/volume.ts
edmaps.rcsb.org doesn't provide DSN6 files anymore. This removes the corresponding UI option.
OK to keep Select in UI if there's only 1 option?
> Remove support for density data from edmaps.rcsb.org

- CHANGELOG.md
- package.json
- src/mol-model-props/computed/chemistry/geometry.ts
- src/mol-model-props/computed/interactions/halogen-bonds.ts
- src/mol-model-props/computed/interactions/hydrogen-bonds.ts
- src/mol-model-props/computed/representations/interactions-inter-unit-cylinder.ts
- src/mol-model-props/computed/representations/interactions-intra-unit-cylinder.ts
Fixes #1163 
This PR refines the way Hydrogen bonds are created and represented when explicit hydrogen atoms atoms are present:
- Donors: the angle between H-Donor-Acceptor must be below the Donor Deviation angle value. This ensures that when H atoms are present on the donor, there is at least one atom positioned in a conic region of angle 90º between the donor and the acceptor
- Acceptors: the H atoms are taken into account to satisfy the geometry of the bond towards the donor. This is the same criteria as for heavy atoms bonded to the acceptor. It ensures that there are no hydrogen atoms on the acceptor that are "in the way" of the hydrogen bond. In other words, the hydrogen bonds is anchored on an unoccupied area of the acceptor.
- Representations: links are made using the closest …
> Take into account explicit hydrogens when creating and representing Hydrogen bonds (regular and weak)

- CHANGELOG.md
- src/mol-canvas3d/controls/trackball.ts
The trackball spin animation is carried out via the same mechanism as pointer drag rotation, which takes the canvas aspect ratio into account via `getRotateFactor`. It might make more sense to set a spin animation to a constant speed in radians per second. The least invasive way to do this is to compensate for `getRotateFactor` when the spin animation is applied.
> Make Trackball spin in radians per second

- CHANGELOG.md
- src/mol-plugin-ui/skin/base/components/misc.scss
Closes #1198 . On node builds, we currently get a Sass deprecation warning due to the latest version update on Sass,  where they started warning users to be more in line with traditional CSS semantics in .scss files.
NOTE: In draft to start, since I don't know how to ensure that this is fully resolved.
> Update  `misc.scss` `msp-no-webgl` syntax to be in line with latest sass requirements

- src/mol-plugin-ui/skin/base/base.scss
- src/mol-plugin-ui/skin/base/components/log.scss
- src/mol-plugin-ui/skin/base/components/misc.scss
Further addressing #1198 
I think I was able to find the rest of the syntax issues. For posterity: one can view the warnings if you switch to a more recent version of sass in package.json (e.g. `^1.77.7`) and then try to `npm run build` on `master`.
> Continue fixing syntax for Sass deprecation of special semantics

- CHANGELOG.md
- src/mol-theme/color/entity-id.ts
Improve entity-id coloring for structures with multiple models from the same source, #1221
> Improve entity-id coloring for structures with multiple models from the same source

- CHANGELOG.md
- src/mol-geo/util/location-iterator.ts
- src/mol-model/structure/structure/structure.ts
- src/mol-model/structure/structure/unit.ts
- src/mol-repr/structure/visual/bond-inter-unit-cylinder.ts
- src/mol-repr/structure/visual/bond-inter-unit-line.ts
- src/mol-repr/structure/visual/bond-intra-unit-cylinder.ts
- src/mol-repr/structure/visual/bond-intra-unit-line.ts
- src/mol-repr/structure/visual/element-cross.ts
- src/mol-repr/structure/visual/element-point.ts
- src/mol-repr/structure/visual/util/bond.ts
- src/mol-repr/structure/visual/util/element.ts
- src/mol-repr/structure/visual/util/link.ts
Avoid calculating bonds for water units when `ignoreHydrogens` is on
- Add `Water` trait to `Unit`
- Remove unsued code from `Structure.ofModel`
- Try reuse boundary in element-cross visual
> Avoid calculating bonds for water units when `ignoreHydrogens` is on

- CHANGELOG.md
- src/apps/viewer/app.ts
- src/mol-plugin-state/actions/structure.ts
- add option to fetch BinaryCIF from AlphaFold DB and make that the default
- I saw @midlik starting to use these files, so I'm assuming that AlphaFold DB finally fully supports BinaryCIF
- PDB-Dev now uses PDB-style identifiers alongside the old style (e.g., PDBDEV_00000012 = 8ZZC)
- future depositions will only have PDB-style identifiers but not the old PDBDEV_00000012 style
- this PR ensures support for both styles
- also note that PDB-Dev currently fails to serve data via the old identifiers but this will be fixed by next Wednesday (in the meantime, [pdb-dev-beta.wwpdb.org](https://pdb-dev-beta.wwpdb.org/bcif/PDBDEV_00000001.bcif) works for testing)
> Support for AlphaFold DB BinaryCIF files and 4-character PDB-Dev IDs

- CHANGELOG.md
- src/mol-util/zip/deflate.ts
- src/mol-util/zip/inflate.ts
- src/mol-util/zip/util.ts
- src/mol-util/zip/zip.ts
- Use `CompressionStream` Browser API when available
// inflating a 44 MB gzip file to 225 MB.
// Using JS
// inflate: 570.8759765625 ms
// inflate: 562.950927734375 ms
// inflate: 595.06591796875 ms
// inflate: 584.8740234375 ms
// inflate: 583.31396484375 ms
// Using DecompressionStream
// inflate: 502.001953125 ms
// inflate: 476.818115234375 ms
// inflate: 476.68701171875 ms
// inflate: 422.319091796875 ms
// inflate: 428.925048828125 ms
closes #580
> compression-api

- CHANGELOG.md
- src/servers/common/util.ts
- src/servers/model/CHANGELOG.md
- src/servers/model/config.ts
- src/servers/model/server/api-web.ts
- src/servers/model/version.ts
- src/servers/volume/CHANGELOG.md
- src/servers/volume/config.ts
- src/servers/volume/server/version.ts
- src/servers/volume/server/web-api.ts
- adds a new endpoint to ModelServer & VolumeServer to report service health
- useful to monitor API status, a non-200 status code makes this easier when used e.g. in Kubernetes
- adds new optional `healthCheckPath` config prop, which can point to 1...n files to ensure that these are readable (i.e. asserting that e.g. both X-ray and EM data are available, depending on the setup)
> ModelServer & VolumeServer: add health-check

- CHANGELOG.md
- src/mol-gl/shader-code.ts
Enables dXrayShaded define when rendering depth. Fixes outlines not showing on opaque representation with xRayShading (on / inverted)
> Enable dXrayShaded define when using depth variant

- CHANGELOG.md
- src/mol-canvas3d/canvas3d.ts
- src/mol-plugin-ui/viewport/simple-settings.tsx
- src/mol-plugin/context.ts
- src/mol-plugin/util/headless-screenshot.ts
Add `resolutionMode` parameter to `Canvas3DContext`
- `scaled`, divides by `devicePixelRatio`
- `native`, no changes
The new default `scaled` helps greatly with rendering performance on high dpi displays and quality is still good enough.
> Resolution mode

- src/apps/mesoscale-explorer/ui/states.tsx
I removed the argument 'ent:' which was breaking the quick style preset
> fix preset coloring in ME

- CHANGELOG.md
- src/extensions/mvs/camera.ts
- src/extensions/mvs/components/primitives.ts
- src/extensions/mvs/helpers/selections.ts
- src/extensions/mvs/helpers/utils.ts
- src/extensions/mvs/load-generic.ts
- src/extensions/mvs/load.ts
- src/extensions/mvs/tree/generic/params-schema.ts
- src/extensions/mvs/tree/mvs/mvs-defaults.ts
- src/extensions/mvs/tree/mvs/mvs-primitives.ts
- src/extensions/mvs/tree/mvs/mvs-tree.ts
- src/extensions/mvs/tree/mvs/param-types.ts
- src/mol-geo/geometry/text/text-builder.ts
- src/mol-math/geometry/primitives/box3d.ts
- src/mol-state/state/builder.ts
- src/mol-state/transform.ts
- src/mol-state/tree/transient.ts
- src/mol-util/param-definition.ts
Adds the ability to define primitives via MVS. See https://github.com/molstar/mol-view-spec/pull/36 for Python builder implementation.
Followup PR(s) will include:
- Additional primitives (e.g., box, arrow, angle, ...)
- TypeScript builder for primitives
- Validation and default values for primitive params
```py
builder.primitives().mesh(
vertices=[
0.0, 0.0, 0.0,
1.0, 0.0, 0.0,
1.0, 1.0, 0.0,
0.0, 1.0, 0.0,
0.0, 0.0, 1.0,
1.0, 0.0, 1.0,
1.0, 1.0, 1.0,
0.0, 1.0, 1.0,
],
indices=[
0, 2, 1, 0, 3, 2,
4, 5, 6, 4, 6, 7,
0, 1, 5, 0, 5, 4,
2, 3, 7, 2, 7, 6,
0, 7, 3, 0, 4, 7,
1, 2, 6, 1, 6, 5,
],
triangle_groups=[0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5],
group_colors={0: "red", 1: "green", 2: "blue", 3: "yellow", 4: "magenta", 5: "cyan"},
group_tooltips={0: "### …
```
> MVS: Primitives MVP

- CHANGELOG.md
- src/mol-gl/shader/text.frag.ts
Remove extra anti-aliasing from text shader. We do enough with post-processing and multi-sampling.
Fixes #1208 & #1306 (hopefully, can't test myself).
> remove extra anti-aliasing from text shader

- CHANGELOG.md
- src/mol-model/structure/structure/mapping.ts
- src/mol-model/structure/structure/structure.ts
- src/mol-model/structure/structure/unit/bonds.ts
- src/mol-repr/structure/complex-visual.ts
- src/mol-repr/structure/representation/ball-and-stick.ts
- src/mol-repr/structure/representation/ellipsoid.ts
- src/mol-repr/structure/representation/line.ts
- src/mol-repr/structure/representation/point.ts
- src/mol-repr/structure/representation/spacefill.ts
- src/mol-repr/structure/visual/bond-inter-unit-line.ts
- src/mol-repr/structure/visual/bond-intra-unit-cylinder.ts
- src/mol-repr/structure/visual/bond-intra-unit-line.ts
- src/mol-repr/structure/visual/element-cross.ts
- src/mol-repr/structure/visual/element-point.ts
- src/mol-repr/structure/visual/ellipsoid-mesh.ts
- src/mol-repr/structure/visual/util/bond.ts
- src/mol-repr/structure/visual/util/element.ts
- src/mol-repr/structure/visual/util/link.ts
- Add `Structure.intraUnitBondMapping`
- Add more structure-based visuals to avoid too many (small) render-objects
- `structure-intra-bond`, `structure-ellipsoid-mesh`, `structure-element-point`, `structure-element-cross`
> Structure visuals

- CHANGELOG.md
- src/mol-canvas3d/passes/postprocessing.ts
A fix for outlines on volume and surface reps not disappearing when includeTransparent is not defined (#1326)
> Fix outlines on volume and surface reps that do not disappearing

- CHANGELOG.md
- src/mol-model-formats/structure/property/bonds/struct_conn.ts
Fixes an issue with partial models returned by the model server. E.g. https://www.ebi.ac.uk/pdbe/model-server/v1/7v08/residueSurroundings?auth_seq_id=3419&pdbx_PDB_ins_code=&auth_asym_id=1&radius=10&encoding=cif previously rendered as
> StructConn.isExhaustive fix

- CHANGELOG.md
- package.json
- src/mol-math/misc.ts
The current version of SWC (1.9.2) cannot handle swap using array destructuring, if the left-hand-side values are not variables but array elements. To make code in molstar as simple as possible, I got rid of any array and use variables for both storing deltas and swapping.
> Refactor value swapping in molstar-math to fix SWC (Next.js) build (#1345)

- CHANGELOG.md
- src/extensions/anvil/prop.ts
- src/extensions/anvil/representation.ts
- turns out adjusting the `isApplicable()` method isn't enough as selection symbols don't check that
- checking based on entity data seemed pretty cheap
- tested for 5xes, 5bna ("Membrane Orientation" hidden, selection symbol returns console warning) and 1brr, 6w6l
> Membrane orientation: improve `isApplicable` check and error handling

- CHANGELOG.md
- src/mol-model-props/computed/chemistry/valence-model.ts
`6KNR` from the linked issue: the cation-Pi interaction that was previously perceived does not appear anymore by default (`assignH` set to `auto`)
This solves issue #1257  with the Valence Model where implicit hydrogens and consequently, charges, can be assigned even if the protonation is known at the level of a single unit.
This code does a traversal of the unit considered for computing the valence model and breaks as soon as an hydrogen has been found. I've considered a possible optimization were the upper bound could be of a few residues (not just one in case there is a capping) before we could assume that the unit has no explicit hydrogen. I don't know if that's a performance improvement worth implementing (it may introduce edge cases on some kind of polymers). 
I've decided against …
> Do not infer implicit Hs when explicit Hs are set #1257

- CHANGELOG.md
- src/mol-gl/shader/chunks/common-frag-params.glsl.ts
Fix for xRay shading with high XrayEdgeFalloff values generating this kind of artifacts
> Xray shading fix for high XrayEdgeFalloff

- CHANGELOG.md
- src/servers/membrane-orientation/config.ts
- src/servers/membrane-orientation/server.ts
- src/servers/membrane-orientation/version.ts
- src/servers/membrane-orientation/web-api.ts
- src/servers/membrane-orientation/web-schema.ts
Minimal server that allows computing the membrane orientation in the context of a MolViewSpec example.
> Membrane Server to generate MolViewSpec data

- CHANGELOG.md
- src/extensions/sb-ncbr/partial-charges/color.ts
- src/extensions/sb-ncbr/partial-charges/property.ts
Changed color for missing partial charges in SB partial charges extension from white to green so that it's obvious that the charge isn't 0 but is instead missing.
> Fix: missing partial charges

- CHANGELOG.md
- src/mol-plugin-ui/controls/slider.tsx
- src/mol-plugin-ui/structure/volume.tsx
- src/mol-util/input/input-observer.ts
> Volume UI improvements

- CHANGELOG.md
- src/mol-math/geometry/lookup3d/common.ts
- src/mol-math/geometry/lookup3d/grid.ts
- src/mol-model/structure/structure/util/lookup3d.ts
- src/mol-theme/color.ts
- src/mol-theme/color/external-structure.ts
Add external-structure theme that colors any geometry by structure properties.
EMD-45213 and PDB entry 9C5B take 200ms with default parameters on my machine:
> add external-structure theme

- CHANGELOG.md
- src/apps/mesoscale-explorer/app.ts
- src/apps/mesoscale-explorer/index.html
- src/apps/mesoscale-explorer/ui/states.tsx
- src/apps/viewer/app.ts
- src/apps/viewer/index.html
- src/mol-plugin-state/actions/structure.ts
wwPDB is rebranding PDB-Dev as PDB-IHM (https://pdb-ihm.org).
This PR renames UI options and constants/functions to the new PDB-IHM name.
pdb-dev.wwpdb.org now redirects to pdb-ihm.org. These changes also ensure that data is fetched from the correct location.
> Rebrand PDB-Dev as PDB-IHM

- CHANGELOG.md
- src/mol-plugin-state/actions/structure.ts
The URL changed. https://data.pdbj.org/pub/pdb/data/structures/divided/mmCIF/tq/1tqn.cif also seems to work but the [download page](https://pdbj.org/mine/resources/1tqn) recommends https://data.pdbjlc1.pdbj.org/pub/pdb/data/structures/divided/mmCIF/tq/1tqn.cif, so going with that.
> Fix PDBj structure data URL

- CHANGELOG.md
- src/extensions/mvs/components/primitives.ts
- src/extensions/mvs/tree/mvs/mvs-builder.ts
- src/extensions/mvs/tree/mvs/mvs-tree-primitives.ts
```py
(
builder.primitives(opacity=0.66)
.ellipse(
color="red",
center=(1, 1, 1),
major_axis=(1.5, 0, 0),
minor_axis=(0, 2, 0),
theta_start=0,
theta_end=math.pi / 2,
tooltip="XY",
)
.ellipse(
color="green",
center=(1, 1, 1),
major_axis_endpoint=(1.5 + 1, 0 + 1, 0 + 1),
minor_axis_endpoint=(0 + 1, 0 + 1, 1 + 1),
theta_start=0,
theta_end=math.pi / 2,
tooltip="XZ",
)
.ellipse(
color="blue",
center=(1, 1, 1),
major_axis=(0, 10, 0),
minor_axis=(0, 0, 1),
radius_major=2,
radius_minor=1,
theta_start=0,
theta_end=math.pi / 2,
tooltip="YZ",
)
.arrow(
start=(1, 1, 1),
end=(1 + 1.5, 1 + 0, 1 + 0),
tube_radius=0.05,
length=1.5 + 0.2,
show_end_cap=True,
color="#ffff00",
tooltip="X",
)
.arrow(
start=(1, 1, 1), direction=(0, 2 + 0.2, 0), tube_radius=0.05, show_end_cap=True, …
```
> MVS: Additional Primitives

- CHANGELOG.md
- src/examples/ihm-restraints/index.html
- src/examples/ihm-restraints/index.tsx
- src/extensions/mvs/_spec/mvs-data.spec.ts
- src/extensions/mvs/helpers/schemas.ts
- src/extensions/mvs/helpers/selections.ts
- src/extensions/mvs/load-helpers.ts
- src/extensions/mvs/tree/mvs/mvs-tree-representations.ts
- src/extensions/mvs/tree/mvs/mvs-tree.ts
- src/extensions/mvs/tree/mvs/param-types.ts
- src/mol-model/structure/structure/properties.ts
- src/mol-script/language/symbol-table/structure-query.ts
- src/mol-script/runtime/query/table.ts
- src/mol-script/script/mol-script/symbols.ts
- webpack.config.js
- webpack.config.production.js
Adds better support for I/HM structure in MolViewSpec
https://pdb-ihm.org/cif/8zz1.cif with crosslink restraints:
> MVS: IHM support

- CHANGELOG.md
- src/extensions/mvs/load-generic.ts
- src/extensions/mvs/load-helpers.ts
- src/extensions/mvs/load.ts
- src/extensions/mvs/tree/molstar/conversion.ts
- src/extensions/mvs/tree/mvs/mvs-builder.ts
- src/extensions/mvs/tree/mvs/mvs-tree-representations.ts
- src/extensions/mvs/tree/mvs/mvs-tree.ts
- src/extensions/mvs/tree/mvs/param-types.ts
```py
download = builder.download(url="https://www.ebi.ac.uk/pdbe/entry-files/1tqn.ccp4")
volume = download.parse(format="map").volume()
(
volume.representation(type="isosurface", relative_isovalue=1, show_wireframe=True)
.color(color="blue")
.opacity(opacity=0.66)
)
```
> MVS: Basic volumetric data support

- CHANGELOG.md
- src/extensions/mvs/load-helpers.ts
- src/extensions/mvs/load.ts
- src/extensions/mvs/tree/mvs/mvs-tree-representations.ts
- src/extensions/mvs/tree/mvs/mvs-tree.ts
- src/mol-plugin-ui/skin/base/components/controls.scss
- src/mol-plugin-ui/skin/base/components/viewport.scss
- src/mol-plugin-ui/viewport/screenshot.tsx
goes with https://github.com/molstar/mol-view-spec/pull/47
```py
structure = builder.download(url=_url_for_mmcif("1tqn")).parse(format="mmcif").model_structure()
structure.component(selector="polymer").representation(type="cartoon").color(color="white")
ligand = structure.component(selector="ligand")
ligand.representation(type="ball_and_stick").color(custom={"molstar_color_theme_name": "element-symbol"})
ligand.focus(up=[0.98, -0.19, 0], direction=[-28.47, -17.66, -16.32], radius=14, radius_extent=5)
volume_data = builder.download(
url="https://www.ebi.ac.uk/pdbe/densities/x-ray/1tqn/box/-22.367,-33.367,-21.634/-7.106,-10.042,-0.937?detail=3"
).parse(format="bcif")
volume_data.volume(channel_id="2FO-FC").representation(
type="isosurface",
relative_isovalue=1.5, …
```
> MVS: Volume Server support + Support carbohydrate representation + Camera section in Screenshot / State

- CHANGELOG.md
- src/extensions/mvs/components/primitives.ts
- src/extensions/mvs/tree/mvs/mvs-tree-primitives.ts
Goes with https://github.com/molstar/mol-view-spec/pull/48
```py
primitives = builder.primitives()
primitives.angle(
a=(2, 1, 1),
b=(1, 1, 1),
c=(2, 2, 1),
section_color="blue",
section_radius_scale=0.5,
vector_color="red",
label_color="green",
)
return PlainTextResponse(builder.get_state())
```
> MVS: Angle primitive

- CHANGELOG.md
- src/extensions/mvs/components/primitives.ts
- src/mol-math/linear-algebra/3d/vec3.ts
. | [Case 1](http://localhost:1338/build/viewer/?mvs-data={%22kind%22:%22single%22,%22root%22:{%22kind%22:%22root%22,%22children%22:[{%22kind%22:%22primitives%22,%22children%22:[{%22kind%22:%22primitive%22,%22params%22:{%22kind%22:%22arrow%22,%22start%22:[0,0,0],%22end%22:[0,-1,0],%22tube_radius%22:0.05,%22show_end_cap%22:true}},{%22kind%22:%22primitive%22,%22params%22:{%22kind%22:%22arrow%22,%22start%22:[0,0,0],%22end%22:[0,1,0],%22tube_radius%22:0.05,%22show_end_cap%22:true}},{%22kind%22:%22primitive%22,%22params%22:{%22kind%22:%22arrow%22,%22start%22:[0,0,0],%22end%22:[-1,0,0],%22tube_radius%22:0.05,%22show_end_cap%22:true}},{%22kind%22:%22primitive%22,%22params%22:{%22kind%22:%22arrow%22,%22start%22:[0,0,0],%22end%22:[1,0,0],%22tube_radius%22:0.05,%22show_end_cap%22:true}}]}]},%22metad …
> Fix arrow primitives orientation and `Vec3.makeRotation` behavior when along [0, -1, 0]

- CHANGELOG.md
- package.json
- src/mol-plugin-ui/controls/parameters.tsx
- src/mol-theme/color/uncertainty.ts
- src/mol-util/color/scale.ts
- Implementation of `ColorScale.createDiscrete`, as discussed in #1458 
- `ColorScale.createDiscrete` used in the `uncertainty` color theme
- Fix color palette shown in the UI (for non-gradient palettes)
- Fix colors description in the UI (when using custom thresholds)
- Fix an edge case in the UI when the user deletes all colors from the color list when interpolation is disabled
Feel free to leave any further comments, I will be glad to improve the code if needed.
> Implement ColorScale.createDiscrete, fix UI color palette bugs

- CHANGELOG.md
- src/mol-model/structure/structure/unit/bonds.ts
Using the ElementBondIterator in the case of the attachment point of a covalent ligand (FMN) in a dimer (8Q5F), we noticed a discrepancy between the chain A (no issue) and the chain B: undefined element index due to an out of bound `otherIndex` for the iterator.
This is due to the fact that, for inter unit bonds, the iteration always begins at index 0 in the array of edges. The mapping to the edge indices is missing in the iteration loop.
> fix: bond iterator starts from the same interbonds for every element

- docs/docs/index.md
Fix command typo: changed 'npm build' to 'npm run build'
> Fix command typo in docs: changed 'npm build' to 'npm run build' 

- CHANGELOG.md
- src/examples/alphafolddb-pae/index.tsx
- src/extensions/model-archive/quality-assessment/behavior.ts
- src/extensions/model-archive/quality-assessment/color/plddt.ts
- src/extensions/model-archive/quality-assessment/color/qmean.ts
- src/extensions/model-archive/quality-assessment/pairwise/plot.ts
- src/extensions/model-archive/quality-assessment/prop.ts
Superseeds https://github.com/molstar/molstar/pull/602
> Update support for QA metrics

- CHANGELOG.md
- package.json
- src/mol-plugin-ui/viewport.tsx
- src/mol-plugin/config.ts
Added an extra config to control whether the screenshot tool pops up in the viewer or not. Seems reasonable to have given most of the other buttons have a toggle. 
Maybe it makes sense to also add one to Refresh / reset button? I don't need to hide it, but happy to add one for others if you all think it does.
> added toggle for hiding screenshot controls

- package.json
This pull request adds an engines field to package.json specifying that Node.js version 18.0.0 or higher is recommended for development.
Since the project depends on Node.js scripts and Node 18+ types (@types/node), specifying an engine range improves clarity for contributors and helps prevent potential version mismatch issues during local development.
This change is non-breaking and only issues a warning if a contributor's local Node.js version is too old.
- Inserted "engines" field after the "bugs" section, following package.json convention.
- Set minimum Node version to >=18.0.0 to match existing dependencies and project usage.
Please let me know if you'd prefer a different Node version constraint or placement. Thank you for considering this small improvement!
> Update Add engines field to specify required Node.js version (>=18.0.0).json

- CHANGELOG.md
- src/servers/volume/CHANGELOG.md
- src/servers/volume/server/query/execute.ts
- src/servers/volume/server/version.ts
Avoids expanding the box when the whole unit cell is required.
> Avoid grid expansion when requiring unit cell on volume server

- CHANGELOG.md
- src/mol-canvas3d/passes/draw.ts
This attempts to fix transparency rendering bug which occurs when occlusion is on, transparencyMode is blended, and depthTexture extension is not available (this is the case when running in NodeJS).
Before:
After:
Please, @arose and/or @giagitom  check if the fix makes sense. I have no idea what the code does but it looked suspicious to have `attach` in `if` and `detach` in `else`, and changing it seems to solve my issue 🤣
> Fix transparency rendering with occlusion in NodeJS

- CHANGELOG.md
- src/mol-canvas3d/canvas3d.ts
- src/mol-canvas3d/passes/draw.ts
- src/mol-canvas3d/passes/illumination.ts
- src/mol-canvas3d/passes/image.ts
- src/mol-canvas3d/passes/pick.ts
- src/mol-canvas3d/passes/postprocessing.ts
- src/mol-canvas3d/passes/ssao.ts
- src/mol-canvas3d/passes/tracing.ts
- src/mol-geo/geometry/direct-volume/direct-volume.ts
- src/mol-geo/geometry/texture-mesh/texture-mesh.ts
- src/mol-gl/compute/histogram-pyramid/reduction.ts
- src/mol-gl/renderable/direct-volume.ts
- src/mol-gl/webgl/context.ts
- src/mol-gl/webgl/extensions.ts
- src/mol-gl/webgl/resources.ts
- src/mol-gl/webgl/texture.ts
- src/mol-gl/webgl/timer.ts
- src/mol-repr/structure/visual/gaussian-density-volume.ts
- src/mol-repr/structure/visual/gaussian-surface-mesh.ts
- src/mol-repr/structure/visual/util/gaussian.ts
- src/mol-repr/volume/isosurface.ts
- Fix missing framebuffer & drawbuffer re-attachments
- Fix missing cube texture re-initialization
- Fix missing extensions reset
- Fix timer clearing edge case
- Add reset support for geometry generated on the GPU
Test by running in debug mode, then hold shift+ctrl+alt and mouse left click. This will trigger a context loss.
> WebGL ContextLost handling improvements

- CHANGELOG.md
- src/apps/viewer/app.ts
- src/cli/mvs/mvs-render.ts
- src/examples/ihm-restraints/index.tsx
- src/examples/mvs-stories/elements/viewer.tsx
- src/extensions/mvs/behavior.ts
- src/extensions/mvs/components/formats.ts
- src/extensions/mvs/load-generic.ts
- src/extensions/mvs/load.ts
- src/extensions/mvs/mvs-data.ts
This changes the way single-state MVS files are loaded. A single-state MVS is now treated the same as a multi-state MVS with one snapshot.
Related changes:
- Merged `loadMVS` options `keepCamera` and `keepSnapshotCamera`, as `keepCamera` lost meaning 
- Added `loadMVS` option `appendSnapshots` ("do not remove current list of snapshots")
- Removed `loadMVS` option `replaceExisting` (is now default, state trees are never combined)
- Drag-and-dropping multiple MVSs loads concatenation of their snapshots (instead of combining state trees into one)
> MVS single state loading

- CHANGELOG.md
- src/extensions/mvs/camera.ts
- src/extensions/mvs/components/formats.ts
- src/mol-plugin-ui/viewport/screenshot.tsx
- src/mol-util/assets.ts
- src/mol-util/camera.ts
> MVS: FoV adjusted position Camera Info & MVSX assets in multi-snapshot states

- CHANGELOG.md
- src/mol-gl/shader-code.ts
- src/mol-gl/shader/chunks/check-picking-alpha.glsl.ts
- src/mol-gl/shader/chunks/common.glsl.ts
Support `pickingAlphaThreshold` when `xrayShaded` is enabled. This allows to pick things below the more transparent parts of xray shaded elements.
> Support `pickingAlphaThreshold` when `xrayShaded` is enabled

- CHANGELOG.md
- src/mol-canvas3d/camera.ts
- src/mol-data/db.ts
- src/mol-gl/_spec/gl.shim.ts
- src/mol-io/writer/encoder.ts
- src/mol-io/writer/writer.ts
- src/mol-math/geometry/boundary-helper.ts
- src/mol-math/geometry/boundary.ts
- src/mol-math/geometry/common.ts
- src/mol-math/geometry/instance-grid.ts
- src/mol-math/geometry/spacegroup/construction.ts
- src/mol-math/linear-algebra/3d/vec3.ts
- src/mol-math/linear-algebra/matrix/principal-axes.ts
- src/mol-model-formats/structure/cube.ts
- src/mol-model/structure/model/properties/utils/residue-set.ts
- src/mol-model/structure/query/queries/modifiers.ts
- src/mol-model/structure/structure/unit/bonds/data.ts
- src/mol-plugin-ui/spec.ts
- src/mol-plugin/util/viewport-screenshot.ts
- tsconfig.commonjs.json
- tsconfig.json
> isolatedModules and fix turbopack build

- src/extensions/dnatco/confal-pyramids/behavior.ts
- src/extensions/dnatco/ntc-tube/behavior.ts
A change how Loci labels are rendered that was introduced by 02cec6f8e6 caused the Loci labels for NtC tube and Confal pyramids to be rendered as verbatim text with no HTML formatting. This PR fixes the issue.
> Fix Loci labels displayed for NtC tube and Confal pyramids

- CHANGELOG.md
- src/mol-model/structure/structure/structure.ts
- src/mol-model/structure/structure/unit.ts
- src/mol-model/structure/structure/unit/resonance.ts
- src/mol-model/structure/structure/unit/rings.ts
Avoid calculating rings for coarse-grained structures via new `Unit.Traits.CoarseGrained`. Use the a trait on purpose instead of just checking unit.model to allow individual units to be caorse-grained or not.
> Avoid calculating rings for coarse-grained structures

- CHANGELOG.md
- src/mol-geo/geometry/mesh/color-smoothing.ts
- src/mol-model/shape/shape.ts
- src/mol-repr/shape/representation.ts
- src/mol-repr/structure/complex-visual.ts
- src/mol-repr/structure/units-visual.ts
- src/mol-repr/volume/representation.ts
Fix group count calculation on visual update. This caused the marking (highlight/select) to be wrong. Only happened after a geometry update.
Fix wrong instance index in `calcMeshColorSmoothing`. This caused overpaint and other themes to be wrong. Only happened for GPU based color smoothing and only if they were enough instances to trigger a instance reordering for the instanceGrid.
> Fix group count calculation on geometry update

- CHANGELOG.md
- docs/mkdocs.yml
- src/extensions/mvs/components/annotation-color-theme.ts
- src/extensions/mvs/components/annotation-prop.ts
- src/extensions/mvs/components/custom-label/visual.ts
- src/extensions/mvs/components/multilayer-color-theme.ts
- src/extensions/mvs/components/selector.ts
- src/extensions/mvs/helpers/label-text.ts
- src/extensions/mvs/helpers/schemas.ts
- src/extensions/mvs/helpers/selections.ts
- src/extensions/mvs/tree/mvs/param-types.ts
- src/mol-math/geometry/spacegroup/construction.ts
- src/mol-math/geometry/symmetry-operator.ts
- src/mol-model-formats/structure/property/assembly.ts
- src/mol-model/structure/structure/element/schema.ts
- src/mol-model/structure/structure/properties.ts
- src/mol-script/language/symbol-table/structure-query.ts
- src/mol-script/runtime/query/table.ts
- src/mol-script/script/mol-script/symbols.ts
- src/mol-theme/label.ts
Support for `instance_id` in inline selectors and MVS annotations. This is used to select individual symmetry instances in crystal symmetry structures and assembly structures.
This goes together with https://github.com/molstar/mol-view-spec/pull/84.
This PR also changes the way symmetry instances are named (SymmetryOperator.name) and introduces alternative identifier (SymmetryOperator.canonicalName).
- Stick to symmetry operators like `1_555` described in [mmCIF dictionary](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_struct_conn.ptnr1_symmetry.html):
- Any translation index <0 or >9 will always be enclosed in parenthesis:
- e.g. `1_(11)15`, `1_1(11)5`, `1_11(15)` instead of ambiguous `1_1115`
- e.g. `1_(-1)1(-1)`
- e.g. `2_454` (stays unchanged)
- Identical to …
> MVS operator_name

- CHANGELOG.md
- src/mol-math/geometry/_spec/box3d.spec.ts
- src/mol-math/geometry/_spec/ray3d.spec.ts
- src/mol-math/geometry/lookup3d/grid.ts
- src/mol-math/geometry/primitives/box3d.ts
- src/mol-math/geometry/primitives/ray3d.ts
This adds tests for box3D nearestIntersectionWithRay3D. 
@arose, I'm not sure if (and how) you want to handle also special cases like 
**1. ray origin inside the box
2. ray missing the box**
> add tests for box3D nearestIntersectionWithRay3D

- CHANGELOG.md
- src/mol-canvas3d/passes/background.ts
- src/mol-canvas3d/passes/bloom.ts
- src/mol-canvas3d/passes/dof.ts
- src/mol-canvas3d/passes/draw.ts
- src/mol-canvas3d/passes/illumination.ts
- src/mol-canvas3d/passes/outline.ts
- src/mol-canvas3d/passes/postprocessing.ts
- src/mol-canvas3d/passes/shadow.ts
Add `enable` param for post-processing effects. If false, no effects are applied.
One use case is for upcoming webxr support. The post-processing effects are often prohibitively expensive in XR so we want an easy way to toggle them.
> add `enable` param for post-processing effects

- CHANGELOG.md
- docs/docs/plugin/managers/markdown-extensions.md
- src/extensions/mvs/camera.ts
- src/extensions/mvs/components/primitives.ts
- src/mol-plugin-state/manager/markdown-extensions.ts
> Markdown Commands and MVS improvements

- CHANGELOG.md
- src/extensions/mvs/components/formats.ts
- src/mol-data/util/hash-functions.ts
This changes archive URI generation in implementation of MVSX loading, from FNV1a to MurmurHash3_128, which is much faster.
Hash compute times for 3j3q.mvsx (54.9MB):
- FNV1a: 492 ms
- MurmurHash3_128-128: 47 ms
> MVSX use Murmur hash

- CHANGELOG.md
- src/mol-canvas3d/passes/dpoit.ts
- src/mol-canvas3d/passes/draw.ts
- src/mol-canvas3d/passes/illumination.ts
This is a small hack to obtain a clean monolayer transparency when using dpoit and `dpoitIterations = 1`
> Add Monolayer transparency (exploiting dpoit)

- CHANGELOG.md
- src/examples/mvs-stories/stories/audio.ts
- src/extensions/mvs/load.ts
- src/extensions/mvs/tree/mvs/mvs-builder.ts
- src/mol-plugin/state.ts
> Execute markdown commands on snapshot load

- src/apps/mesoscale-explorer/app.ts
- src/mol-canvas3d/canvas3d.ts
- src/mol-canvas3d/controls/trackball.ts
- src/mol-plugin-ui/controls.tsx
- src/mol-plugin-ui/viewport/help.tsx
- src/mol-plugin/behavior.ts
- src/mol-plugin/behavior/dynamic/state.ts
- src/mol-plugin/spec.ts
- add SnapshotControls behavior
- don't save behaviors in mesoscale explorer snapshots (@corredD we will need to remove the "behaviors" from the existing ME session state.json files)
- add canvas3d/trackball attribs that are configurable but are not saved in the state like props
In the WebXR branch I will add bindings for controllers
> Trackball & Snapshot handling tweaks

- CHANGELOG.md
- src/examples/mvs-stories/stories/animation.ts
- src/extensions/mvs/README.md
- src/extensions/mvs/camera.ts
- src/extensions/mvs/helpers/animation.ts
- src/extensions/mvs/load.ts
- src/extensions/mvs/tree/animation/animation-tree.ts
- src/extensions/mvs/tree/generic/tree-schema.ts
- src/extensions/mvs/tree/mvs/mvs-tree-primitives.ts
- src/mol-canvas3d/passes/background.ts
- src/mol-plugin-state/animation/built-in/state-snapshots.ts
- src/mol-util/assets.ts
- src/mol-util/error-context.ts
> MVS: Color map interpolation & canvas backgrounds

- CHANGELOG.md
- src/extensions/rcsb/validation-report/prop.ts
A new endpoint is now available that provides the validation xml files in plain text (optionally transmitted with gzip encoding). This will allow removing the old endpoint in rcsb infrastructure.
> Use new validation/view endpoint at files.rcsb.org

- CHANGELOG.md
- src/mol-canvas3d/passes/pick.ts
- src/mol-geo/geometry/picking.ts
- src/mol-repr/shape/representation.ts
- src/mol-repr/structure/visual/carbohydrate-link-cylinder.ts
- src/mol-repr/structure/visual/carbohydrate-symbol-mesh.ts
- src/mol-repr/structure/visual/carbohydrate-terminal-link-cylinder.ts
- src/mol-repr/structure/visual/util/bond.ts
- src/mol-repr/structure/visual/util/element.ts
- src/mol-repr/structure/visual/util/nucleotide.ts
- src/mol-repr/structure/visual/util/polymer.ts
- src/mol-repr/volume/dot.ts
- src/mol-repr/volume/isosurface.ts
- src/mol-repr/volume/segment.ts
- src/mol-repr/volume/slice.ts
Improve picking of objects with many groups. If there are too many groups (currently >=2^24-2) pick whole instance/object instead of picking nothing.
Partly addresses #1623.
> improve picking of objects with many groups
